// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/judgment/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/judgment/usecase.go -destination=mocks/application/judgment/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	judgment "github.com/qkitzero/fitness-service/internal/application/judgment"
	judgment0 "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	organization "github.com/qkitzero/fitness-service/internal/domain/organization"
	gomock "go.uber.org/mock/gomock"
)

// MockJudgmentUsecase is a mock of JudgmentUsecase interface.
type MockJudgmentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockJudgmentUsecaseMockRecorder
	isgomock struct{}
}

// MockJudgmentUsecaseMockRecorder is the mock recorder for MockJudgmentUsecase.
type MockJudgmentUsecaseMockRecorder struct {
	mock *MockJudgmentUsecase
}

// NewMockJudgmentUsecase creates a new mock instance.
func NewMockJudgmentUsecase(ctrl *gomock.Controller) *MockJudgmentUsecase {
	mock := &MockJudgmentUsecase{ctrl: ctrl}
	mock.recorder = &MockJudgmentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudgmentUsecase) EXPECT() *MockJudgmentUsecaseMockRecorder {
	return m.recorder
}

// DeletePrescription mocks base method.
func (m *MockJudgmentUsecase) DeletePrescription(ctx context.Context, measurementID measurement.MeasurementID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrescription", ctx, measurementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrescription indicates an expected call of DeletePrescription.
func (mr *MockJudgmentUsecaseMockRecorder) DeletePrescription(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrescription", reflect.TypeOf((*MockJudgmentUsecase)(nil).DeletePrescription), ctx, measurementID)
}

// GetJudgment mocks base method.
func (m *MockJudgmentUsecase) GetJudgment(ctx context.Context, measurementID measurement.MeasurementID) (judgment.JudgmentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJudgment", ctx, measurementID)
	ret0, _ := ret[0].(judgment.JudgmentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJudgment indicates an expected call of GetJudgment.
func (mr *MockJudgmentUsecaseMockRecorder) GetJudgment(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJudgment", reflect.TypeOf((*MockJudgmentUsecase)(nil).GetJudgment), ctx, measurementID)
}

// ListOrganizationJudgments mocks base method.
func (m *MockJudgmentUsecase) ListOrganizationJudgments(ctx context.Context, organizationID organization.OrganizationID, includeInactive bool) ([]judgment.OrganizationJudgmentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationJudgments", ctx, organizationID, includeInactive)
	ret0, _ := ret[0].([]judgment.OrganizationJudgmentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationJudgments indicates an expected call of ListOrganizationJudgments.
func (mr *MockJudgmentUsecaseMockRecorder) ListOrganizationJudgments(ctx, organizationID, includeInactive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationJudgments", reflect.TypeOf((*MockJudgmentUsecase)(nil).ListOrganizationJudgments), ctx, organizationID, includeInactive)
}

// UpsertJudgmentAdvice mocks base method.
func (m *MockJudgmentUsecase) UpsertJudgmentAdvice(ctx context.Context, measurementID measurement.MeasurementID, patch judgment.AdvicePatch) (judgment0.Judgment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertJudgmentAdvice", ctx, measurementID, patch)
	ret0, _ := ret[0].(judgment0.Judgment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertJudgmentAdvice indicates an expected call of UpsertJudgmentAdvice.
func (mr *MockJudgmentUsecaseMockRecorder) UpsertJudgmentAdvice(ctx, measurementID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertJudgmentAdvice", reflect.TypeOf((*MockJudgmentUsecase)(nil).UpsertJudgmentAdvice), ctx, measurementID, patch)
}

// UpsertPrescription mocks base method.
func (m *MockJudgmentUsecase) UpsertPrescription(ctx context.Context, measurementID measurement.MeasurementID, menus []judgment.PrescribedMenuInput) (judgment0.Prescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPrescription", ctx, measurementID, menus)
	ret0, _ := ret[0].(judgment0.Prescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPrescription indicates an expected call of UpsertPrescription.
func (mr *MockJudgmentUsecaseMockRecorder) UpsertPrescription(ctx, measurementID, menus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPrescription", reflect.TypeOf((*MockJudgmentUsecase)(nil).UpsertPrescription), ctx, measurementID, menus)
}
