// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/training_menu_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/training_menu_repository.go -destination=mocks/domain/training/mock_training_menu_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockTrainingMenuRepository is a mock of TrainingMenuRepository interface.
type MockTrainingMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockTrainingMenuRepositoryMockRecorder is the mock recorder for MockTrainingMenuRepository.
type MockTrainingMenuRepositoryMockRecorder struct {
	mock *MockTrainingMenuRepository
}

// NewMockTrainingMenuRepository creates a new mock instance.
func NewMockTrainingMenuRepository(ctrl *gomock.Controller) *MockTrainingMenuRepository {
	mock := &MockTrainingMenuRepository{ctrl: ctrl}
	mock.recorder = &MockTrainingMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingMenuRepository) EXPECT() *MockTrainingMenuRepositoryMockRecorder {
	return m.recorder
}

// FindByIDs mocks base method.
func (m *MockTrainingMenuRepository) FindByIDs(ctx context.Context, trainingMenuIDs []training.TrainingMenuID) ([]training.TrainingMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, trainingMenuIDs)
	ret0, _ := ret[0].([]training.TrainingMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockTrainingMenuRepositoryMockRecorder) FindByIDs(ctx, trainingMenuIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockTrainingMenuRepository)(nil).FindByIDs), ctx, trainingMenuIDs)
}

// List mocks base method.
func (m *MockTrainingMenuRepository) List(ctx context.Context) ([]training.TrainingMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]training.TrainingMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTrainingMenuRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTrainingMenuRepository)(nil).List), ctx)
}
