// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/fixed_menu.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/fixed_menu.go -destination=mocks/domain/training/mock_fixed_menu.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockFixedMenu is a mock of FixedMenu interface.
type MockFixedMenu struct {
	ctrl     *gomock.Controller
	recorder *MockFixedMenuMockRecorder
	isgomock struct{}
}

// MockFixedMenuMockRecorder is the mock recorder for MockFixedMenu.
type MockFixedMenuMockRecorder struct {
	mock *MockFixedMenu
}

// NewMockFixedMenu creates a new mock instance.
func NewMockFixedMenu(ctrl *gomock.Controller) *MockFixedMenu {
	mock := &MockFixedMenu{ctrl: ctrl}
	mock.recorder = &MockFixedMenuMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixedMenu) EXPECT() *MockFixedMenuMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockFixedMenu) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockFixedMenuMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockFixedMenu)(nil).CreatedAt))
}

// SortOrder mocks base method.
func (m *MockFixedMenu) SortOrder() training.SortOrder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortOrder")
	ret0, _ := ret[0].(training.SortOrder)
	return ret0
}

// SortOrder indicates an expected call of SortOrder.
func (mr *MockFixedMenuMockRecorder) SortOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortOrder", reflect.TypeOf((*MockFixedMenu)(nil).SortOrder))
}

// TrainingMenuID mocks base method.
func (m *MockFixedMenu) TrainingMenuID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// TrainingMenuID indicates an expected call of TrainingMenuID.
func (mr *MockFixedMenuMockRecorder) TrainingMenuID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuID", reflect.TypeOf((*MockFixedMenu)(nil).TrainingMenuID))
}

// UpdatedAt mocks base method.
func (m *MockFixedMenu) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockFixedMenuMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockFixedMenu)(nil).UpdatedAt))
}
