// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/prescription_rule_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/prescription_rule_repository.go -destination=mocks/domain/training/mock_prescription_rule_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockPrescriptionRuleRepository is a mock of PrescriptionRuleRepository interface.
type MockPrescriptionRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockPrescriptionRuleRepositoryMockRecorder is the mock recorder for MockPrescriptionRuleRepository.
type MockPrescriptionRuleRepositoryMockRecorder struct {
	mock *MockPrescriptionRuleRepository
}

// NewMockPrescriptionRuleRepository creates a new mock instance.
func NewMockPrescriptionRuleRepository(ctrl *gomock.Controller) *MockPrescriptionRuleRepository {
	mock := &MockPrescriptionRuleRepository{ctrl: ctrl}
	mock.recorder = &MockPrescriptionRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescriptionRuleRepository) EXPECT() *MockPrescriptionRuleRepositoryMockRecorder {
	return m.recorder
}

// ListAgeDecadeMenus mocks base method.
func (m *MockPrescriptionRuleRepository) ListAgeDecadeMenus(ctx context.Context) ([]training.AgeDecadeMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgeDecadeMenus", ctx)
	ret0, _ := ret[0].([]training.AgeDecadeMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgeDecadeMenus indicates an expected call of ListAgeDecadeMenus.
func (mr *MockPrescriptionRuleRepositoryMockRecorder) ListAgeDecadeMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgeDecadeMenus", reflect.TypeOf((*MockPrescriptionRuleRepository)(nil).ListAgeDecadeMenus), ctx)
}

// ListElementMenus mocks base method.
func (m *MockPrescriptionRuleRepository) ListElementMenus(ctx context.Context) ([]training.ElementMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListElementMenus", ctx)
	ret0, _ := ret[0].([]training.ElementMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListElementMenus indicates an expected call of ListElementMenus.
func (mr *MockPrescriptionRuleRepositoryMockRecorder) ListElementMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListElementMenus", reflect.TypeOf((*MockPrescriptionRuleRepository)(nil).ListElementMenus), ctx)
}

// ListFixedMenus mocks base method.
func (m *MockPrescriptionRuleRepository) ListFixedMenus(ctx context.Context) ([]training.FixedMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFixedMenus", ctx)
	ret0, _ := ret[0].([]training.FixedMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFixedMenus indicates an expected call of ListFixedMenus.
func (mr *MockPrescriptionRuleRepositoryMockRecorder) ListFixedMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFixedMenus", reflect.TypeOf((*MockPrescriptionRuleRepository)(nil).ListFixedMenus), ctx)
}
