// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/training_menu.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/training_menu.go -destination=mocks/domain/training/mock_training_menu.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockTrainingMenu is a mock of TrainingMenu interface.
type MockTrainingMenu struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingMenuMockRecorder
	isgomock struct{}
}

// MockTrainingMenuMockRecorder is the mock recorder for MockTrainingMenu.
type MockTrainingMenuMockRecorder struct {
	mock *MockTrainingMenu
}

// NewMockTrainingMenu creates a new mock instance.
func NewMockTrainingMenu(ctrl *gomock.Controller) *MockTrainingMenu {
	mock := &MockTrainingMenu{ctrl: ctrl}
	mock.recorder = &MockTrainingMenuMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingMenu) EXPECT() *MockTrainingMenuMockRecorder {
	return m.recorder
}

// Amount mocks base method.
func (m *MockTrainingMenu) Amount() training.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Amount")
	ret0, _ := ret[0].(training.Amount)
	return ret0
}

// Amount indicates an expected call of Amount.
func (mr *MockTrainingMenuMockRecorder) Amount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Amount", reflect.TypeOf((*MockTrainingMenu)(nil).Amount))
}

// Code mocks base method.
func (m *MockTrainingMenu) Code() training.Code {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(training.Code)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockTrainingMenuMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockTrainingMenu)(nil).Code))
}

// CreatedAt mocks base method.
func (m *MockTrainingMenu) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockTrainingMenuMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockTrainingMenu)(nil).CreatedAt))
}

// Element mocks base method.
func (m *MockTrainingMenu) Element() measurementitem.Element {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Element")
	ret0, _ := ret[0].(measurementitem.Element)
	return ret0
}

// Element indicates an expected call of Element.
func (mr *MockTrainingMenuMockRecorder) Element() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Element", reflect.TypeOf((*MockTrainingMenu)(nil).Element))
}

// ID mocks base method.
func (m *MockTrainingMenu) ID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockTrainingMenuMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockTrainingMenu)(nil).ID))
}

// Instruction mocks base method.
func (m *MockTrainingMenu) Instruction() training.Instruction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instruction")
	ret0, _ := ret[0].(training.Instruction)
	return ret0
}

// Instruction indicates an expected call of Instruction.
func (mr *MockTrainingMenuMockRecorder) Instruction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instruction", reflect.TypeOf((*MockTrainingMenu)(nil).Instruction))
}

// Name mocks base method.
func (m *MockTrainingMenu) Name() training.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(training.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTrainingMenuMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTrainingMenu)(nil).Name))
}

// Part mocks base method.
func (m *MockTrainingMenu) Part() training.Part {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Part")
	ret0, _ := ret[0].(training.Part)
	return ret0
}

// Part indicates an expected call of Part.
func (mr *MockTrainingMenuMockRecorder) Part() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Part", reflect.TypeOf((*MockTrainingMenu)(nil).Part))
}

// Sets mocks base method.
func (m *MockTrainingMenu) Sets() training.Sets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sets")
	ret0, _ := ret[0].(training.Sets)
	return ret0
}

// Sets indicates an expected call of Sets.
func (mr *MockTrainingMenuMockRecorder) Sets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sets", reflect.TypeOf((*MockTrainingMenu)(nil).Sets))
}

// Unit mocks base method.
func (m *MockTrainingMenu) Unit() training.Unit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unit")
	ret0, _ := ret[0].(training.Unit)
	return ret0
}

// Unit indicates an expected call of Unit.
func (mr *MockTrainingMenuMockRecorder) Unit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unit", reflect.TypeOf((*MockTrainingMenu)(nil).Unit))
}

// UpdatedAt mocks base method.
func (m *MockTrainingMenu) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockTrainingMenuMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockTrainingMenu)(nil).UpdatedAt))
}
