// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/age_decade_menu.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/age_decade_menu.go -destination=mocks/domain/training/mock_age_decade_menu.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockAgeDecadeMenu is a mock of AgeDecadeMenu interface.
type MockAgeDecadeMenu struct {
	ctrl     *gomock.Controller
	recorder *MockAgeDecadeMenuMockRecorder
	isgomock struct{}
}

// MockAgeDecadeMenuMockRecorder is the mock recorder for MockAgeDecadeMenu.
type MockAgeDecadeMenuMockRecorder struct {
	mock *MockAgeDecadeMenu
}

// NewMockAgeDecadeMenu creates a new mock instance.
func NewMockAgeDecadeMenu(ctrl *gomock.Controller) *MockAgeDecadeMenu {
	mock := &MockAgeDecadeMenu{ctrl: ctrl}
	mock.recorder = &MockAgeDecadeMenuMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgeDecadeMenu) EXPECT() *MockAgeDecadeMenuMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockAgeDecadeMenu) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockAgeDecadeMenuMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockAgeDecadeMenu)(nil).CreatedAt))
}

// Decade mocks base method.
func (m *MockAgeDecadeMenu) Decade() training.Decade {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decade")
	ret0, _ := ret[0].(training.Decade)
	return ret0
}

// Decade indicates an expected call of Decade.
func (mr *MockAgeDecadeMenuMockRecorder) Decade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decade", reflect.TypeOf((*MockAgeDecadeMenu)(nil).Decade))
}

// SortOrder mocks base method.
func (m *MockAgeDecadeMenu) SortOrder() training.SortOrder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortOrder")
	ret0, _ := ret[0].(training.SortOrder)
	return ret0
}

// SortOrder indicates an expected call of SortOrder.
func (mr *MockAgeDecadeMenuMockRecorder) SortOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortOrder", reflect.TypeOf((*MockAgeDecadeMenu)(nil).SortOrder))
}

// TrainingMenuID mocks base method.
func (m *MockAgeDecadeMenu) TrainingMenuID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// TrainingMenuID indicates an expected call of TrainingMenuID.
func (mr *MockAgeDecadeMenuMockRecorder) TrainingMenuID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuID", reflect.TypeOf((*MockAgeDecadeMenu)(nil).TrainingMenuID))
}

// UpdatedAt mocks base method.
func (m *MockAgeDecadeMenu) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockAgeDecadeMenuMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockAgeDecadeMenu)(nil).UpdatedAt))
}
