// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/training/element_menu.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/training/element_menu.go -destination=mocks/domain/training/mock_element_menu.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockElementMenu is a mock of ElementMenu interface.
type MockElementMenu struct {
	ctrl     *gomock.Controller
	recorder *MockElementMenuMockRecorder
	isgomock struct{}
}

// MockElementMenuMockRecorder is the mock recorder for MockElementMenu.
type MockElementMenuMockRecorder struct {
	mock *MockElementMenu
}

// NewMockElementMenu creates a new mock instance.
func NewMockElementMenu(ctrl *gomock.Controller) *MockElementMenu {
	mock := &MockElementMenu{ctrl: ctrl}
	mock.recorder = &MockElementMenuMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElementMenu) EXPECT() *MockElementMenuMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockElementMenu) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockElementMenuMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockElementMenu)(nil).CreatedAt))
}

// Element mocks base method.
func (m *MockElementMenu) Element() measurementitem.Element {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Element")
	ret0, _ := ret[0].(measurementitem.Element)
	return ret0
}

// Element indicates an expected call of Element.
func (mr *MockElementMenuMockRecorder) Element() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Element", reflect.TypeOf((*MockElementMenu)(nil).Element))
}

// Level mocks base method.
func (m *MockElementMenu) Level() training.Level {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Level")
	ret0, _ := ret[0].(training.Level)
	return ret0
}

// Level indicates an expected call of Level.
func (mr *MockElementMenuMockRecorder) Level() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Level", reflect.TypeOf((*MockElementMenu)(nil).Level))
}

// Part mocks base method.
func (m *MockElementMenu) Part() training.Part {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Part")
	ret0, _ := ret[0].(training.Part)
	return ret0
}

// Part indicates an expected call of Part.
func (mr *MockElementMenuMockRecorder) Part() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Part", reflect.TypeOf((*MockElementMenu)(nil).Part))
}

// TrainingMenuID mocks base method.
func (m *MockElementMenu) TrainingMenuID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// TrainingMenuID indicates an expected call of TrainingMenuID.
func (mr *MockElementMenuMockRecorder) TrainingMenuID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuID", reflect.TypeOf((*MockElementMenu)(nil).TrainingMenuID))
}

// UpdatedAt mocks base method.
func (m *MockElementMenu) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockElementMenuMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockElementMenu)(nil).UpdatedAt))
}
