// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/measurementitem/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/measurementitem/usecase.go -destination=mocks/application/measurementitem/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementItemUsecase is a mock of MeasurementItemUsecase interface.
type MockMeasurementItemUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementItemUsecaseMockRecorder
	isgomock struct{}
}

// MockMeasurementItemUsecaseMockRecorder is the mock recorder for MockMeasurementItemUsecase.
type MockMeasurementItemUsecaseMockRecorder struct {
	mock *MockMeasurementItemUsecase
}

// NewMockMeasurementItemUsecase creates a new mock instance.
func NewMockMeasurementItemUsecase(ctrl *gomock.Controller) *MockMeasurementItemUsecase {
	mock := &MockMeasurementItemUsecase{ctrl: ctrl}
	mock.recorder = &MockMeasurementItemUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementItemUsecase) EXPECT() *MockMeasurementItemUsecaseMockRecorder {
	return m.recorder
}

// ListMeasurementItems mocks base method.
func (m *MockMeasurementItemUsecase) ListMeasurementItems(ctx context.Context) ([]measurementitem.MeasurementItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeasurementItems", ctx)
	ret0, _ := ret[0].([]measurementitem.MeasurementItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeasurementItems indicates an expected call of ListMeasurementItems.
func (mr *MockMeasurementItemUsecaseMockRecorder) ListMeasurementItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeasurementItems", reflect.TypeOf((*MockMeasurementItemUsecase)(nil).ListMeasurementItems), ctx)
}
