// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/measurementitem/measurement_item.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/measurementitem/measurement_item.go -destination=mocks/domain/measurementitem/mock_measurement_item.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementItem is a mock of MeasurementItem interface.
type MockMeasurementItem struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementItemMockRecorder
	isgomock struct{}
}

// MockMeasurementItemMockRecorder is the mock recorder for MockMeasurementItem.
type MockMeasurementItemMockRecorder struct {
	mock *MockMeasurementItem
}

// NewMockMeasurementItem creates a new mock instance.
func NewMockMeasurementItem(ctrl *gomock.Controller) *MockMeasurementItem {
	mock := &MockMeasurementItem{ctrl: ctrl}
	mock.recorder = &MockMeasurementItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementItem) EXPECT() *MockMeasurementItemMockRecorder {
	return m.recorder
}

// Bilateral mocks base method.
func (m *MockMeasurementItem) Bilateral() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bilateral")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Bilateral indicates an expected call of Bilateral.
func (mr *MockMeasurementItemMockRecorder) Bilateral() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bilateral", reflect.TypeOf((*MockMeasurementItem)(nil).Bilateral))
}

// Category mocks base method.
func (m *MockMeasurementItem) Category() measurementitem.Category {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category")
	ret0, _ := ret[0].(measurementitem.Category)
	return ret0
}

// Category indicates an expected call of Category.
func (mr *MockMeasurementItemMockRecorder) Category() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockMeasurementItem)(nil).Category))
}

// Code mocks base method.
func (m *MockMeasurementItem) Code() measurementitem.Code {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(measurementitem.Code)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockMeasurementItemMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockMeasurementItem)(nil).Code))
}

// CreatedAt mocks base method.
func (m *MockMeasurementItem) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockMeasurementItemMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockMeasurementItem)(nil).CreatedAt))
}

// ID mocks base method.
func (m *MockMeasurementItem) ID() measurementitem.MeasurementItemID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(measurementitem.MeasurementItemID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockMeasurementItemMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockMeasurementItem)(nil).ID))
}

// Name mocks base method.
func (m *MockMeasurementItem) Name() measurementitem.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(measurementitem.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMeasurementItemMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMeasurementItem)(nil).Name))
}

// TrialCount mocks base method.
func (m *MockMeasurementItem) TrialCount() measurementitem.TrialCount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrialCount")
	ret0, _ := ret[0].(measurementitem.TrialCount)
	return ret0
}

// TrialCount indicates an expected call of TrialCount.
func (mr *MockMeasurementItemMockRecorder) TrialCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrialCount", reflect.TypeOf((*MockMeasurementItem)(nil).TrialCount))
}

// Unit mocks base method.
func (m *MockMeasurementItem) Unit() measurementitem.Unit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unit")
	ret0, _ := ret[0].(measurementitem.Unit)
	return ret0
}

// Unit indicates an expected call of Unit.
func (mr *MockMeasurementItemMockRecorder) Unit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unit", reflect.TypeOf((*MockMeasurementItem)(nil).Unit))
}

// UpdatedAt mocks base method.
func (m *MockMeasurementItem) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockMeasurementItemMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockMeasurementItem)(nil).UpdatedAt))
}

// ValueType mocks base method.
func (m *MockMeasurementItem) ValueType() measurementitem.ValueType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueType")
	ret0, _ := ret[0].(measurementitem.ValueType)
	return ret0
}

// ValueType indicates an expected call of ValueType.
func (mr *MockMeasurementItemMockRecorder) ValueType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueType", reflect.TypeOf((*MockMeasurementItem)(nil).ValueType))
}
