// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/measurementitem/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/measurementitem/repository.go -destination=mocks/domain/measurementitem/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementItemRepository is a mock of MeasurementItemRepository interface.
type MockMeasurementItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementItemRepositoryMockRecorder
	isgomock struct{}
}

// MockMeasurementItemRepositoryMockRecorder is the mock recorder for MockMeasurementItemRepository.
type MockMeasurementItemRepositoryMockRecorder struct {
	mock *MockMeasurementItemRepository
}

// NewMockMeasurementItemRepository creates a new mock instance.
func NewMockMeasurementItemRepository(ctrl *gomock.Controller) *MockMeasurementItemRepository {
	mock := &MockMeasurementItemRepository{ctrl: ctrl}
	mock.recorder = &MockMeasurementItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementItemRepository) EXPECT() *MockMeasurementItemRepositoryMockRecorder {
	return m.recorder
}

// FindByIDs mocks base method.
func (m *MockMeasurementItemRepository) FindByIDs(ctx context.Context, measurementItemIDs []measurementitem.MeasurementItemID) ([]measurementitem.MeasurementItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ctx, measurementItemIDs)
	ret0, _ := ret[0].([]measurementitem.MeasurementItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockMeasurementItemRepositoryMockRecorder) FindByIDs(ctx, measurementItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockMeasurementItemRepository)(nil).FindByIDs), ctx, measurementItemIDs)
}

// List mocks base method.
func (m *MockMeasurementItemRepository) List(ctx context.Context) ([]measurementitem.MeasurementItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]measurementitem.MeasurementItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMeasurementItemRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMeasurementItemRepository)(nil).List), ctx)
}
