syntax = "proto3";

package measurement.v1;

import "google/api/annotations.proto";
import "google/type/date.proto";

option go_package = "github.com/qkitzero/fitness-service/gen/go/measurement/v1";

service MeasurementService {
  rpc CreateMeasurement(CreateMeasurementRequest) returns (CreateMeasurementResponse) {
    option (google.api.http) = {
      post: "/v1/customer/{customer_id}/measurement"
      body: "*"
    };
  }
  rpc GetMeasurement(GetMeasurementRequest) returns (GetMeasurementResponse) {
    option (google.api.http) = {get: "/v1/measurement/{measurement_id}"};
  }
  rpc ListMeasurements(ListMeasurementsRequest) returns (ListMeasurementsResponse) {
    option (google.api.http) = {get: "/v1/customer/{customer_id}/measurements"};
  }
  rpc UpdateMeasurement(UpdateMeasurementRequest) returns (UpdateMeasurementResponse) {
    option (google.api.http) = {
      put: "/v1/measurement/{measurement_id}"
      body: "*"
    };
  }
  rpc DeleteMeasurement(DeleteMeasurementRequest) returns (DeleteMeasurementResponse) {
    option (google.api.http) = {delete: "/v1/measurement/{measurement_id}"};
  }
}

enum Side {
  SIDE_UNSPECIFIED = 0;
  SIDE_NONE = 1;
  SIDE_LEFT = 2;
  SIDE_RIGHT = 3;
}

message MeasurementValue {
  uint32 trial_index = 1;
  Side side = 2;
  optional double value = 3;
  optional double value_secondary = 4;
  optional string value_choice = 5;
}

message MeasurementEntry {
  string measurement_item_id = 1;
  bool unmeasurable = 2;
  optional string note = 3;
  repeated MeasurementValue values = 4;
}

message Measurement {
  string measurement_id = 1;
  string customer_id = 2;
  google.type.Date measured_on = 3;
  string measured_by = 4;
  uint32 age_at_measurement = 5;
  string updated_by = 6;
  bool is_draft = 7;
  repeated MeasurementEntry entries = 8;
}

message CreateMeasurementRequest {
  string customer_id = 1;
  google.type.Date measured_on = 2;
  string measured_by = 3;
  bool is_draft = 4;
  repeated MeasurementEntry entries = 5;
}

message CreateMeasurementResponse {
  string measurement_id = 1;
}

message GetMeasurementRequest {
  string measurement_id = 1;
}

message GetMeasurementResponse {
  Measurement measurement = 1;
}

message ListMeasurementsRequest {
  string customer_id = 1;
}

message ListMeasurementsResponse {
  repeated Measurement measurements = 1;
}

message UpdateMeasurementRequest {
  string measurement_id = 1;
  google.type.Date measured_on = 2;
  string measured_by = 3;
  bool is_draft = 4;
  repeated MeasurementEntry entries = 5;
}

message UpdateMeasurementResponse {
  Measurement measurement = 1;
}

message DeleteMeasurementRequest {
  string measurement_id = 1;
}

message DeleteMeasurementResponse {}
