// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/organization/organization.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/organization/organization.go -destination=mocks/domain/organization/mock_organization.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	organization "github.com/qkitzero/fitness-service/internal/domain/organization"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganization is a mock of Organization interface.
type MockOrganization struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationMockRecorder
	isgomock struct{}
}

// MockOrganizationMockRecorder is the mock recorder for MockOrganization.
type MockOrganizationMockRecorder struct {
	mock *MockOrganization
}

// NewMockOrganization creates a new mock instance.
func NewMockOrganization(ctrl *gomock.Controller) *MockOrganization {
	mock := &MockOrganization{ctrl: ctrl}
	mock.recorder = &MockOrganizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganization) EXPECT() *MockOrganizationMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockOrganization) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockOrganizationMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockOrganization)(nil).CreatedAt))
}

// GroupID mocks base method.
func (m *MockOrganization) GroupID() organization.GroupID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupID")
	ret0, _ := ret[0].(organization.GroupID)
	return ret0
}

// GroupID indicates an expected call of GroupID.
func (mr *MockOrganizationMockRecorder) GroupID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupID", reflect.TypeOf((*MockOrganization)(nil).GroupID))
}

// ID mocks base method.
func (m *MockOrganization) ID() organization.OrganizationID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(organization.OrganizationID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockOrganizationMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockOrganization)(nil).ID))
}

// Name mocks base method.
func (m *MockOrganization) Name() organization.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(organization.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockOrganizationMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockOrganization)(nil).Name))
}

// Update mocks base method.
func (m *MockOrganization) Update(name organization.Name) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", name)
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationMockRecorder) Update(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganization)(nil).Update), name)
}

// UpdatedAt mocks base method.
func (m *MockOrganization) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockOrganizationMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockOrganization)(nil).UpdatedAt))
}
