// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/customer.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/customer.go -destination=mocks/domain/customer/mock_customer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomer is a mock of Customer interface.
type MockCustomer struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerMockRecorder
	isgomock struct{}
}

// MockCustomerMockRecorder is the mock recorder for MockCustomer.
type MockCustomerMockRecorder struct {
	mock *MockCustomer
}

// NewMockCustomer creates a new mock instance.
func NewMockCustomer(ctrl *gomock.Controller) *MockCustomer {
	mock := &MockCustomer{ctrl: ctrl}
	mock.recorder = &MockCustomerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomer) EXPECT() *MockCustomerMockRecorder {
	return m.recorder
}

// BirthDate mocks base method.
func (m *MockCustomer) BirthDate() customer.BirthDate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BirthDate")
	ret0, _ := ret[0].(customer.BirthDate)
	return ret0
}

// BirthDate indicates an expected call of BirthDate.
func (mr *MockCustomerMockRecorder) BirthDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BirthDate", reflect.TypeOf((*MockCustomer)(nil).BirthDate))
}

// CreatedAt mocks base method.
func (m *MockCustomer) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockCustomerMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockCustomer)(nil).CreatedAt))
}

// Gender mocks base method.
func (m *MockCustomer) Gender() customer.Gender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gender")
	ret0, _ := ret[0].(customer.Gender)
	return ret0
}

// Gender indicates an expected call of Gender.
func (mr *MockCustomerMockRecorder) Gender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gender", reflect.TypeOf((*MockCustomer)(nil).Gender))
}

// GroupID mocks base method.
func (m *MockCustomer) GroupID() customer.GroupID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupID")
	ret0, _ := ret[0].(customer.GroupID)
	return ret0
}

// GroupID indicates an expected call of GroupID.
func (mr *MockCustomerMockRecorder) GroupID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupID", reflect.TypeOf((*MockCustomer)(nil).GroupID))
}

// ID mocks base method.
func (m *MockCustomer) ID() customer.CustomerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(customer.CustomerID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockCustomerMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockCustomer)(nil).ID))
}

// Name mocks base method.
func (m *MockCustomer) Name() customer.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(customer.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCustomerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCustomer)(nil).Name))
}

// NameKana mocks base method.
func (m *MockCustomer) NameKana() customer.NameKana {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameKana")
	ret0, _ := ret[0].(customer.NameKana)
	return ret0
}

// NameKana indicates an expected call of NameKana.
func (mr *MockCustomerMockRecorder) NameKana() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameKana", reflect.TypeOf((*MockCustomer)(nil).NameKana))
}

// Update mocks base method.
func (m *MockCustomer) Update(name customer.Name, nameKana customer.NameKana, gender customer.Gender, birthDate customer.BirthDate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", name, nameKana, gender, birthDate)
}

// Update indicates an expected call of Update.
func (mr *MockCustomerMockRecorder) Update(name, nameKana, gender, birthDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomer)(nil).Update), name, nameKana, gender, birthDate)
}

// UpdatedAt mocks base method.
func (m *MockCustomer) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockCustomerMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockCustomer)(nil).UpdatedAt))
}
