// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/customer.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/customer.go -destination=mocks/domain/customer/mock_customer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	tenant "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomer is a mock of Customer interface.
type MockCustomer struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerMockRecorder
	isgomock struct{}
}

// MockCustomerMockRecorder is the mock recorder for MockCustomer.
type MockCustomerMockRecorder struct {
	mock *MockCustomer
}

// NewMockCustomer creates a new mock instance.
func NewMockCustomer(ctrl *gomock.Controller) *MockCustomer {
	mock := &MockCustomer{ctrl: ctrl}
	mock.recorder = &MockCustomerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomer) EXPECT() *MockCustomerMockRecorder {
	return m.recorder
}

// BirthDate mocks base method.
func (m *MockCustomer) BirthDate() customer.BirthDate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BirthDate")
	ret0, _ := ret[0].(customer.BirthDate)
	return ret0
}

// BirthDate indicates an expected call of BirthDate.
func (mr *MockCustomerMockRecorder) BirthDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BirthDate", reflect.TypeOf((*MockCustomer)(nil).BirthDate))
}

// Building mocks base method.
func (m *MockCustomer) Building() *customer.Building {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Building")
	ret0, _ := ret[0].(*customer.Building)
	return ret0
}

// Building indicates an expected call of Building.
func (mr *MockCustomerMockRecorder) Building() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Building", reflect.TypeOf((*MockCustomer)(nil).Building))
}

// City mocks base method.
func (m *MockCustomer) City() *customer.City {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "City")
	ret0, _ := ret[0].(*customer.City)
	return ret0
}

// City indicates an expected call of City.
func (mr *MockCustomerMockRecorder) City() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "City", reflect.TypeOf((*MockCustomer)(nil).City))
}

// CreatedAt mocks base method.
func (m *MockCustomer) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockCustomerMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockCustomer)(nil).CreatedAt))
}

// Email mocks base method.
func (m *MockCustomer) Email() *customer.Email {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email")
	ret0, _ := ret[0].(*customer.Email)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockCustomerMockRecorder) Email() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockCustomer)(nil).Email))
}

// EmergencyContactName mocks base method.
func (m *MockCustomer) EmergencyContactName() *customer.EmergencyContactName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmergencyContactName")
	ret0, _ := ret[0].(*customer.EmergencyContactName)
	return ret0
}

// EmergencyContactName indicates an expected call of EmergencyContactName.
func (mr *MockCustomerMockRecorder) EmergencyContactName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmergencyContactName", reflect.TypeOf((*MockCustomer)(nil).EmergencyContactName))
}

// EmergencyContactPhone mocks base method.
func (m *MockCustomer) EmergencyContactPhone() *customer.Phone {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmergencyContactPhone")
	ret0, _ := ret[0].(*customer.Phone)
	return ret0
}

// EmergencyContactPhone indicates an expected call of EmergencyContactPhone.
func (mr *MockCustomerMockRecorder) EmergencyContactPhone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmergencyContactPhone", reflect.TypeOf((*MockCustomer)(nil).EmergencyContactPhone))
}

// EmergencyContactRelationship mocks base method.
func (m *MockCustomer) EmergencyContactRelationship() *customer.EmergencyContactRelationship {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmergencyContactRelationship")
	ret0, _ := ret[0].(*customer.EmergencyContactRelationship)
	return ret0
}

// EmergencyContactRelationship indicates an expected call of EmergencyContactRelationship.
func (mr *MockCustomerMockRecorder) EmergencyContactRelationship() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmergencyContactRelationship", reflect.TypeOf((*MockCustomer)(nil).EmergencyContactRelationship))
}

// Gender mocks base method.
func (m *MockCustomer) Gender() customer.Gender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gender")
	ret0, _ := ret[0].(customer.Gender)
	return ret0
}

// Gender indicates an expected call of Gender.
func (mr *MockCustomerMockRecorder) Gender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gender", reflect.TypeOf((*MockCustomer)(nil).Gender))
}

// ID mocks base method.
func (m *MockCustomer) ID() customer.CustomerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(customer.CustomerID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockCustomerMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockCustomer)(nil).ID))
}

// IsActive mocks base method.
func (m *MockCustomer) IsActive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsActive indicates an expected call of IsActive.
func (mr *MockCustomerMockRecorder) IsActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockCustomer)(nil).IsActive))
}

// Name mocks base method.
func (m *MockCustomer) Name() customer.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(customer.Name)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCustomerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCustomer)(nil).Name))
}

// NameKana mocks base method.
func (m *MockCustomer) NameKana() customer.NameKana {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NameKana")
	ret0, _ := ret[0].(customer.NameKana)
	return ret0
}

// NameKana indicates an expected call of NameKana.
func (mr *MockCustomerMockRecorder) NameKana() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NameKana", reflect.TypeOf((*MockCustomer)(nil).NameKana))
}

// Phone mocks base method.
func (m *MockCustomer) Phone() *customer.Phone {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Phone")
	ret0, _ := ret[0].(*customer.Phone)
	return ret0
}

// Phone indicates an expected call of Phone.
func (mr *MockCustomerMockRecorder) Phone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phone", reflect.TypeOf((*MockCustomer)(nil).Phone))
}

// PostalCode mocks base method.
func (m *MockCustomer) PostalCode() *customer.PostalCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostalCode")
	ret0, _ := ret[0].(*customer.PostalCode)
	return ret0
}

// PostalCode indicates an expected call of PostalCode.
func (mr *MockCustomerMockRecorder) PostalCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostalCode", reflect.TypeOf((*MockCustomer)(nil).PostalCode))
}

// Prefecture mocks base method.
func (m *MockCustomer) Prefecture() *customer.Prefecture {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prefecture")
	ret0, _ := ret[0].(*customer.Prefecture)
	return ret0
}

// Prefecture indicates an expected call of Prefecture.
func (mr *MockCustomerMockRecorder) Prefecture() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefecture", reflect.TypeOf((*MockCustomer)(nil).Prefecture))
}

// SetActive mocks base method.
func (m *MockCustomer) SetActive(active bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetActive", active)
}

// SetActive indicates an expected call of SetActive.
func (mr *MockCustomerMockRecorder) SetActive(active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockCustomer)(nil).SetActive), active)
}

// Street mocks base method.
func (m *MockCustomer) Street() *customer.Street {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Street")
	ret0, _ := ret[0].(*customer.Street)
	return ret0
}

// Street indicates an expected call of Street.
func (mr *MockCustomerMockRecorder) Street() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Street", reflect.TypeOf((*MockCustomer)(nil).Street))
}

// TenantID mocks base method.
func (m *MockCustomer) TenantID() tenant.TenantID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantID")
	ret0, _ := ret[0].(tenant.TenantID)
	return ret0
}

// TenantID indicates an expected call of TenantID.
func (mr *MockCustomerMockRecorder) TenantID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantID", reflect.TypeOf((*MockCustomer)(nil).TenantID))
}

// Update mocks base method.
func (m *MockCustomer) Update(name customer.Name, nameKana customer.NameKana, gender customer.Gender, birthDate customer.BirthDate, phone *customer.Phone, email *customer.Email, postalCode *customer.PostalCode, prefecture *customer.Prefecture, city *customer.City, street *customer.Street, building *customer.Building, emergencyContactName *customer.EmergencyContactName, emergencyContactRelationship *customer.EmergencyContactRelationship, emergencyContactPhone *customer.Phone) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", name, nameKana, gender, birthDate, phone, email, postalCode, prefecture, city, street, building, emergencyContactName, emergencyContactRelationship, emergencyContactPhone)
}

// Update indicates an expected call of Update.
func (mr *MockCustomerMockRecorder) Update(name, nameKana, gender, birthDate, phone, email, postalCode, prefecture, city, street, building, emergencyContactName, emergencyContactRelationship, emergencyContactPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomer)(nil).Update), name, nameKana, gender, birthDate, phone, email, postalCode, prefecture, city, street, building, emergencyContactName, emergencyContactRelationship, emergencyContactPhone)
}

// UpdatedAt mocks base method.
func (m *MockCustomer) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockCustomerMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockCustomer)(nil).UpdatedAt))
}
