// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/repository.go -destination=mocks/domain/customer/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	organization "github.com/qkitzero/fitness-service/internal/domain/organization"
	tenant "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerRepository) Create(ctx context.Context, arg1 customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomerRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockCustomerRepository) Delete(ctx context.Context, customerID customer.CustomerID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, customerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerRepositoryMockRecorder) Delete(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerRepository)(nil).Delete), ctx, customerID)
}

// FindByID mocks base method.
func (m *MockCustomerRepository) FindByID(ctx context.Context, customerID customer.CustomerID) (customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, customerID)
	ret0, _ := ret[0].(customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCustomerRepositoryMockRecorder) FindByID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCustomerRepository)(nil).FindByID), ctx, customerID)
}

// ListByOrganizationID mocks base method.
func (m *MockCustomerRepository) ListByOrganizationID(ctx context.Context, organizationID organization.OrganizationID, includeInactive bool) ([]customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganizationID", ctx, organizationID, includeInactive)
	ret0, _ := ret[0].([]customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrganizationID indicates an expected call of ListByOrganizationID.
func (mr *MockCustomerRepositoryMockRecorder) ListByOrganizationID(ctx, organizationID, includeInactive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganizationID", reflect.TypeOf((*MockCustomerRepository)(nil).ListByOrganizationID), ctx, organizationID, includeInactive)
}

// ListByTenantID mocks base method.
func (m *MockCustomerRepository) ListByTenantID(ctx context.Context, tenantID tenant.TenantID, includeInactive bool) ([]customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenantID", ctx, tenantID, includeInactive)
	ret0, _ := ret[0].([]customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenantID indicates an expected call of ListByTenantID.
func (mr *MockCustomerRepositoryMockRecorder) ListByTenantID(ctx, tenantID, includeInactive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenantID", reflect.TypeOf((*MockCustomerRepository)(nil).ListByTenantID), ctx, tenantID, includeInactive)
}

// Update mocks base method.
func (m *MockCustomerRepository) Update(ctx context.Context, arg1 customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerRepository)(nil).Update), ctx, arg1)
}

// UpdateActive mocks base method.
func (m *MockCustomerRepository) UpdateActive(ctx context.Context, arg1 customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActive", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActive indicates an expected call of UpdateActive.
func (mr *MockCustomerRepositoryMockRecorder) UpdateActive(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActive", reflect.TypeOf((*MockCustomerRepository)(nil).UpdateActive), ctx, arg1)
}
