// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/tenant/profile.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/tenant/profile.go -destination=mocks/domain/tenant/mock_profile.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	address "github.com/qkitzero/fitness-service/internal/domain/address"
	contact "github.com/qkitzero/fitness-service/internal/domain/contact"
	tenant "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockProfile is a mock of Profile interface.
type MockProfile struct {
	ctrl     *gomock.Controller
	recorder *MockProfileMockRecorder
	isgomock struct{}
}

// MockProfileMockRecorder is the mock recorder for MockProfile.
type MockProfileMockRecorder struct {
	mock *MockProfile
}

// NewMockProfile creates a new mock instance.
func NewMockProfile(ctrl *gomock.Controller) *MockProfile {
	mock := &MockProfile{ctrl: ctrl}
	mock.recorder = &MockProfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfile) EXPECT() *MockProfileMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockProfile) Address() address.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(address.Address)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockProfileMockRecorder) Address() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockProfile)(nil).Address))
}

// CreatedAt mocks base method.
func (m *MockProfile) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockProfileMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockProfile)(nil).CreatedAt))
}

// Email mocks base method.
func (m *MockProfile) Email() *contact.Email {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Email")
	ret0, _ := ret[0].(*contact.Email)
	return ret0
}

// Email indicates an expected call of Email.
func (mr *MockProfileMockRecorder) Email() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Email", reflect.TypeOf((*MockProfile)(nil).Email))
}

// HomepageURL mocks base method.
func (m *MockProfile) HomepageURL() *tenant.HomepageURL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HomepageURL")
	ret0, _ := ret[0].(*tenant.HomepageURL)
	return ret0
}

// HomepageURL indicates an expected call of HomepageURL.
func (mr *MockProfileMockRecorder) HomepageURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HomepageURL", reflect.TypeOf((*MockProfile)(nil).HomepageURL))
}

// Note mocks base method.
func (m *MockProfile) Note() *tenant.Note {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Note")
	ret0, _ := ret[0].(*tenant.Note)
	return ret0
}

// Note indicates an expected call of Note.
func (mr *MockProfileMockRecorder) Note() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Note", reflect.TypeOf((*MockProfile)(nil).Note))
}

// Phone mocks base method.
func (m *MockProfile) Phone() *contact.Phone {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Phone")
	ret0, _ := ret[0].(*contact.Phone)
	return ret0
}

// Phone indicates an expected call of Phone.
func (mr *MockProfileMockRecorder) Phone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phone", reflect.TypeOf((*MockProfile)(nil).Phone))
}

// TenantID mocks base method.
func (m *MockProfile) TenantID() tenant.TenantID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantID")
	ret0, _ := ret[0].(tenant.TenantID)
	return ret0
}

// TenantID indicates an expected call of TenantID.
func (mr *MockProfileMockRecorder) TenantID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantID", reflect.TypeOf((*MockProfile)(nil).TenantID))
}

// Update mocks base method.
func (m *MockProfile) Update(addr address.Address, phone *contact.Phone, email *contact.Email, homepageURL *tenant.HomepageURL, note *tenant.Note) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", addr, phone, email, homepageURL, note)
}

// Update indicates an expected call of Update.
func (mr *MockProfileMockRecorder) Update(addr, phone, email, homepageURL, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfile)(nil).Update), addr, phone, email, homepageURL, note)
}

// UpdatedAt mocks base method.
func (m *MockProfile) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockProfileMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockProfile)(nil).UpdatedAt))
}
