// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/tenant/profile_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/tenant/profile_repository.go -destination=mocks/domain/tenant/mock_profile_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tenant "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileRepository is a mock of ProfileRepository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// FindByTenantID mocks base method.
func (m *MockProfileRepository) FindByTenantID(ctx context.Context, tenantID tenant.TenantID) (tenant.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(tenant.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenantID indicates an expected call of FindByTenantID.
func (mr *MockProfileRepositoryMockRecorder) FindByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenantID", reflect.TypeOf((*MockProfileRepository)(nil).FindByTenantID), ctx, tenantID)
}

// Upsert mocks base method.
func (m *MockProfileRepository) Upsert(ctx context.Context, profile tenant.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProfileRepositoryMockRecorder) Upsert(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProfileRepository)(nil).Upsert), ctx, profile)
}
