INSERT INTO element_menus (element, part, level, training_menu_id, created_at, updated_at)
SELECT seed.element, seed.part, seed.level, training_menus.id, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
FROM (
  VALUES
    ('muscle_strength', 'upper_limb', 1, 'arm_raise'),
    ('muscle_strength', 'upper_limb', 2, 'wall_push_up'),
    ('muscle_strength', 'upper_limb', 3, 'knee_push_up'),
    ('muscle_strength', 'upper_limb', 4, 'push_up'),
    ('muscle_strength', 'upper_limb', 5, 'feet_elevated_push_up'),
    ('muscle_strength', 'lower_limb', 1, 'assisted_sit_to_stand'),
    ('muscle_strength', 'lower_limb', 2, 'chair_squat'),
    ('muscle_strength', 'lower_limb', 3, 'squat'),
    ('muscle_strength', 'lower_limb', 4, 'split_squat'),
    ('muscle_strength', 'lower_limb', 5, 'single_leg_squat'),
    ('muscle_strength', 'whole_body', 1, 'supine_bridge'),
    ('muscle_strength', 'whole_body', 2, 'trunk_stabilize'),
    ('muscle_strength', 'whole_body', 3, 'front_plank'),
    ('muscle_strength', 'whole_body', 4, 'side_plank'),
    ('muscle_strength', 'whole_body', 5, 'leg_raise_plank'),
    ('muscle_endurance', 'lower_limb', 1, 'seated_march'),
    ('muscle_endurance', 'lower_limb', 2, 'standing_march'),
    ('muscle_endurance', 'lower_limb', 3, 'heel_raise'),
    ('muscle_endurance', 'lower_limb', 4, 'step_up_down'),
    ('muscle_endurance', 'lower_limb', 5, 'wall_sit_hold'),
    ('muscle_endurance', 'whole_body', 1, 'seated_arm_swing'),
    ('muscle_endurance', 'whole_body', 2, 'arm_leg_march'),
    ('muscle_endurance', 'whole_body', 3, 'sit_to_stand_repeat'),
    ('muscle_endurance', 'whole_body', 4, 'squat_and_press'),
    ('muscle_endurance', 'whole_body', 5, 'slow_burpee'),
    ('flexibility', 'upper_limb', 1, 'shoulder_shrug'),
    ('flexibility', 'upper_limb', 2, 'shoulder_rotation'),
    ('flexibility', 'upper_limb', 3, 'chest_stretch'),
    ('flexibility', 'upper_limb', 4, 'overhead_side_stretch'),
    ('flexibility', 'upper_limb', 5, 'back_clasp_stretch'),
    ('flexibility', 'lower_limb', 1, 'seated_ankle_pump'),
    ('flexibility', 'lower_limb', 2, 'seated_hamstring_stretch'),
    ('flexibility', 'lower_limb', 3, 'calf_stretch'),
    ('flexibility', 'lower_limb', 4, 'hip_flexor_stretch'),
    ('flexibility', 'lower_limb', 5, 'long_sitting_forward_bend'),
    ('agility', 'lower_limb', 1, 'seated_toe_tap'),
    ('agility', 'lower_limb', 2, 'standing_toe_tap'),
    ('agility', 'lower_limb', 3, 'side_step_touch'),
    ('agility', 'lower_limb', 4, 'quick_side_step'),
    ('agility', 'lower_limb', 5, 'lateral_hop'),
    ('agility', 'whole_body', 1, 'seated_reaction_reach'),
    ('agility', 'whole_body', 2, 'standing_reaction_reach'),
    ('agility', 'whole_body', 3, 'step_and_turn'),
    ('agility', 'whole_body', 4, 'zigzag_walk'),
    ('agility', 'whole_body', 5, 'agility_shuttle'),
    ('balance', 'lower_limb', 1, 'seated_weight_shift'),
    ('balance', 'lower_limb', 2, 'assisted_one_leg_stand'),
    ('balance', 'lower_limb', 3, 'one_leg_stand'),
    ('balance', 'lower_limb', 4, 'closed_eye_one_leg_stand'),
    ('balance', 'lower_limb', 5, 'cushion_one_leg_stand'),
    ('balance', 'whole_body', 1, 'seated_trunk_sway'),
    ('balance', 'whole_body', 2, 'feet_together_stand'),
    ('balance', 'whole_body', 3, 'tandem_stand'),
    ('balance', 'whole_body', 4, 'tandem_walk'),
    ('balance', 'whole_body', 5, 'single_leg_reach'),
    ('mobility', 'whole_body', 1, 'sit_to_stand_transfer'),
    ('mobility', 'whole_body', 2, 'assisted_walk'),
    ('mobility', 'whole_body', 3, 'indoor_walk'),
    ('mobility', 'whole_body', 4, 'outdoor_walk'),
    ('mobility', 'whole_body', 5, 'brisk_walk')
) AS seed (element, part, level, code)
JOIN training_menus ON training_menus.code = seed.code;

INSERT INTO fixed_menus (sort_order, training_menu_id, created_at, updated_at)
SELECT seed.sort_order, training_menus.id, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
FROM (
  VALUES
    (1, 'shoulder_rotation'),
    (2, 'calf_stretch'),
    (3, 'chair_squat'),
    (4, 'standing_march'),
    (5, 'indoor_walk')
) AS seed (sort_order, code)
JOIN training_menus ON training_menus.code = seed.code;

INSERT INTO age_decade_menus (decade, sort_order, training_menu_id, created_at, updated_at)
SELECT seed.decade, seed.sort_order, training_menus.id, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'
FROM (
  VALUES
    (10, 1, 'push_up'),
    (10, 2, 'split_squat'),
    (10, 3, 'lateral_hop'),
    (10, 4, 'single_leg_reach'),
    (10, 5, 'brisk_walk'),
    (20, 1, 'push_up'),
    (20, 2, 'squat'),
    (20, 3, 'quick_side_step'),
    (20, 4, 'tandem_walk'),
    (20, 5, 'brisk_walk'),
    (30, 1, 'knee_push_up'),
    (30, 2, 'squat'),
    (30, 3, 'side_step_touch'),
    (30, 4, 'tandem_walk'),
    (30, 5, 'outdoor_walk'),
    (40, 1, 'knee_push_up'),
    (40, 2, 'squat'),
    (40, 3, 'side_step_touch'),
    (40, 4, 'tandem_stand'),
    (40, 5, 'outdoor_walk'),
    (50, 1, 'wall_push_up'),
    (50, 2, 'chair_squat'),
    (50, 3, 'standing_toe_tap'),
    (50, 4, 'tandem_stand'),
    (50, 5, 'outdoor_walk'),
    (60, 1, 'wall_push_up'),
    (60, 2, 'chair_squat'),
    (60, 3, 'standing_toe_tap'),
    (60, 4, 'one_leg_stand'),
    (60, 5, 'indoor_walk'),
    (70, 1, 'arm_raise'),
    (70, 2, 'chair_squat'),
    (70, 3, 'standing_march'),
    (70, 4, 'assisted_one_leg_stand'),
    (70, 5, 'indoor_walk'),
    (80, 1, 'arm_raise'),
    (80, 2, 'assisted_sit_to_stand'),
    (80, 3, 'seated_march'),
    (80, 4, 'assisted_one_leg_stand'),
    (80, 5, 'assisted_walk'),
    (90, 1, 'shoulder_shrug'),
    (90, 2, 'assisted_sit_to_stand'),
    (90, 3, 'seated_march'),
    (90, 4, 'seated_weight_shift'),
    (90, 5, 'sit_to_stand_transfer')
) AS seed (decade, sort_order, code)
JOIN training_menus ON training_menus.code = seed.code;
