DELETE FROM age_decade_menus
USING (
  VALUES
    (10, 1),
    (10, 2),
    (10, 3),
    (10, 4),
    (10, 5),
    (20, 1),
    (20, 2),
    (20, 3),
    (20, 4),
    (20, 5),
    (30, 1),
    (30, 2),
    (30, 3),
    (30, 4),
    (30, 5),
    (40, 1),
    (40, 2),
    (40, 3),
    (40, 4),
    (40, 5),
    (50, 1),
    (50, 2),
    (50, 3),
    (50, 4),
    (50, 5),
    (60, 1),
    (60, 2),
    (60, 3),
    (60, 4),
    (60, 5),
    (70, 1),
    (70, 2),
    (70, 3),
    (70, 4),
    (70, 5),
    (80, 1),
    (80, 2),
    (80, 3),
    (80, 4),
    (80, 5),
    (90, 1),
    (90, 2),
    (90, 3),
    (90, 4),
    (90, 5)
) AS seed (decade, sort_order)
WHERE age_decade_menus.decade = seed.decade
  AND age_decade_menus.sort_order = seed.sort_order;

DELETE FROM fixed_menus
WHERE sort_order IN (1, 2, 3, 4, 5);

DELETE FROM element_menus
USING (
  VALUES
    ('muscle_strength', 'upper_limb', 1),
    ('muscle_strength', 'upper_limb', 2),
    ('muscle_strength', 'upper_limb', 3),
    ('muscle_strength', 'upper_limb', 4),
    ('muscle_strength', 'upper_limb', 5),
    ('muscle_strength', 'lower_limb', 1),
    ('muscle_strength', 'lower_limb', 2),
    ('muscle_strength', 'lower_limb', 3),
    ('muscle_strength', 'lower_limb', 4),
    ('muscle_strength', 'lower_limb', 5),
    ('muscle_strength', 'whole_body', 1),
    ('muscle_strength', 'whole_body', 2),
    ('muscle_strength', 'whole_body', 3),
    ('muscle_strength', 'whole_body', 4),
    ('muscle_strength', 'whole_body', 5),
    ('muscle_endurance', 'lower_limb', 1),
    ('muscle_endurance', 'lower_limb', 2),
    ('muscle_endurance', 'lower_limb', 3),
    ('muscle_endurance', 'lower_limb', 4),
    ('muscle_endurance', 'lower_limb', 5),
    ('muscle_endurance', 'whole_body', 1),
    ('muscle_endurance', 'whole_body', 2),
    ('muscle_endurance', 'whole_body', 3),
    ('muscle_endurance', 'whole_body', 4),
    ('muscle_endurance', 'whole_body', 5),
    ('flexibility', 'upper_limb', 1),
    ('flexibility', 'upper_limb', 2),
    ('flexibility', 'upper_limb', 3),
    ('flexibility', 'upper_limb', 4),
    ('flexibility', 'upper_limb', 5),
    ('flexibility', 'lower_limb', 1),
    ('flexibility', 'lower_limb', 2),
    ('flexibility', 'lower_limb', 3),
    ('flexibility', 'lower_limb', 4),
    ('flexibility', 'lower_limb', 5),
    ('agility', 'lower_limb', 1),
    ('agility', 'lower_limb', 2),
    ('agility', 'lower_limb', 3),
    ('agility', 'lower_limb', 4),
    ('agility', 'lower_limb', 5),
    ('agility', 'whole_body', 1),
    ('agility', 'whole_body', 2),
    ('agility', 'whole_body', 3),
    ('agility', 'whole_body', 4),
    ('agility', 'whole_body', 5),
    ('balance', 'lower_limb', 1),
    ('balance', 'lower_limb', 2),
    ('balance', 'lower_limb', 3),
    ('balance', 'lower_limb', 4),
    ('balance', 'lower_limb', 5),
    ('balance', 'whole_body', 1),
    ('balance', 'whole_body', 2),
    ('balance', 'whole_body', 3),
    ('balance', 'whole_body', 4),
    ('balance', 'whole_body', 5),
    ('mobility', 'whole_body', 1),
    ('mobility', 'whole_body', 2),
    ('mobility', 'whole_body', 3),
    ('mobility', 'whole_body', 4),
    ('mobility', 'whole_body', 5)
) AS seed (element, part, level)
WHERE element_menus.element = seed.element
  AND element_menus.part = seed.part
  AND element_menus.level = seed.level;
