// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/training/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/training/usecase.go -destination=mocks/application/training/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockTrainingMenuUsecase is a mock of TrainingMenuUsecase interface.
type MockTrainingMenuUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingMenuUsecaseMockRecorder
	isgomock struct{}
}

// MockTrainingMenuUsecaseMockRecorder is the mock recorder for MockTrainingMenuUsecase.
type MockTrainingMenuUsecaseMockRecorder struct {
	mock *MockTrainingMenuUsecase
}

// NewMockTrainingMenuUsecase creates a new mock instance.
func NewMockTrainingMenuUsecase(ctrl *gomock.Controller) *MockTrainingMenuUsecase {
	mock := &MockTrainingMenuUsecase{ctrl: ctrl}
	mock.recorder = &MockTrainingMenuUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingMenuUsecase) EXPECT() *MockTrainingMenuUsecaseMockRecorder {
	return m.recorder
}

// ListTrainingMenus mocks base method.
func (m *MockTrainingMenuUsecase) ListTrainingMenus(ctx context.Context) ([]training.TrainingMenu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainingMenus", ctx)
	ret0, _ := ret[0].([]training.TrainingMenu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainingMenus indicates an expected call of ListTrainingMenus.
func (mr *MockTrainingMenuUsecaseMockRecorder) ListTrainingMenus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainingMenus", reflect.TypeOf((*MockTrainingMenuUsecase)(nil).ListTrainingMenus), ctx)
}
