// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/measurement/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/measurement/repository.go -destination=mocks/domain/measurement/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementRepository is a mock of MeasurementRepository interface.
type MockMeasurementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementRepositoryMockRecorder
	isgomock struct{}
}

// MockMeasurementRepositoryMockRecorder is the mock recorder for MockMeasurementRepository.
type MockMeasurementRepositoryMockRecorder struct {
	mock *MockMeasurementRepository
}

// NewMockMeasurementRepository creates a new mock instance.
func NewMockMeasurementRepository(ctrl *gomock.Controller) *MockMeasurementRepository {
	mock := &MockMeasurementRepository{ctrl: ctrl}
	mock.recorder = &MockMeasurementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementRepository) EXPECT() *MockMeasurementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMeasurementRepository) Create(ctx context.Context, arg1 measurement.Measurement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMeasurementRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeasurementRepository)(nil).Create), ctx, arg1)
}

// Delete mocks base method.
func (m *MockMeasurementRepository) Delete(ctx context.Context, measurementID measurement.MeasurementID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, measurementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMeasurementRepositoryMockRecorder) Delete(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMeasurementRepository)(nil).Delete), ctx, measurementID)
}

// FindByID mocks base method.
func (m *MockMeasurementRepository) FindByID(ctx context.Context, measurementID measurement.MeasurementID) (measurement.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, measurementID)
	ret0, _ := ret[0].(measurement.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMeasurementRepositoryMockRecorder) FindByID(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMeasurementRepository)(nil).FindByID), ctx, measurementID)
}

// ListByCustomerID mocks base method.
func (m *MockMeasurementRepository) ListByCustomerID(ctx context.Context, customerID customer.CustomerID) ([]measurement.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCustomerID", ctx, customerID)
	ret0, _ := ret[0].([]measurement.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCustomerID indicates an expected call of ListByCustomerID.
func (mr *MockMeasurementRepositoryMockRecorder) ListByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCustomerID", reflect.TypeOf((*MockMeasurementRepository)(nil).ListByCustomerID), ctx, customerID)
}

// Update mocks base method.
func (m *MockMeasurementRepository) Update(ctx context.Context, arg1 measurement.Measurement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMeasurementRepositoryMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeasurementRepository)(nil).Update), ctx, arg1)
}
