// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/measurement/measurement_entry.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/measurement/measurement_entry.go -destination=mocks/domain/measurement/mock_measurement_entry.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementEntry is a mock of MeasurementEntry interface.
type MockMeasurementEntry struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementEntryMockRecorder
	isgomock struct{}
}

// MockMeasurementEntryMockRecorder is the mock recorder for MockMeasurementEntry.
type MockMeasurementEntryMockRecorder struct {
	mock *MockMeasurementEntry
}

// NewMockMeasurementEntry creates a new mock instance.
func NewMockMeasurementEntry(ctrl *gomock.Controller) *MockMeasurementEntry {
	mock := &MockMeasurementEntry{ctrl: ctrl}
	mock.recorder = &MockMeasurementEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementEntry) EXPECT() *MockMeasurementEntryMockRecorder {
	return m.recorder
}

// ExpectedValueCount mocks base method.
func (m *MockMeasurementEntry) ExpectedValueCount() (int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectedValueCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ExpectedValueCount indicates an expected call of ExpectedValueCount.
func (mr *MockMeasurementEntryMockRecorder) ExpectedValueCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectedValueCount", reflect.TypeOf((*MockMeasurementEntry)(nil).ExpectedValueCount))
}

// MeasurementItemID mocks base method.
func (m *MockMeasurementEntry) MeasurementItemID() measurementitem.MeasurementItemID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasurementItemID")
	ret0, _ := ret[0].(measurementitem.MeasurementItemID)
	return ret0
}

// MeasurementItemID indicates an expected call of MeasurementItemID.
func (mr *MockMeasurementEntryMockRecorder) MeasurementItemID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasurementItemID", reflect.TypeOf((*MockMeasurementEntry)(nil).MeasurementItemID))
}

// Note mocks base method.
func (m *MockMeasurementEntry) Note() *measurement.Note {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Note")
	ret0, _ := ret[0].(*measurement.Note)
	return ret0
}

// Note indicates an expected call of Note.
func (mr *MockMeasurementEntryMockRecorder) Note() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Note", reflect.TypeOf((*MockMeasurementEntry)(nil).Note))
}

// Unmeasurable mocks base method.
func (m *MockMeasurementEntry) Unmeasurable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmeasurable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Unmeasurable indicates an expected call of Unmeasurable.
func (mr *MockMeasurementEntryMockRecorder) Unmeasurable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmeasurable", reflect.TypeOf((*MockMeasurementEntry)(nil).Unmeasurable))
}

// Values mocks base method.
func (m *MockMeasurementEntry) Values() []measurement.MeasurementValue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Values")
	ret0, _ := ret[0].([]measurement.MeasurementValue)
	return ret0
}

// Values indicates an expected call of Values.
func (mr *MockMeasurementEntryMockRecorder) Values() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Values", reflect.TypeOf((*MockMeasurementEntry)(nil).Values))
}
