// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/measurement/measurement.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/measurement/measurement.go -destination=mocks/domain/measurement/mock_measurement.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	staff "github.com/qkitzero/fitness-service/internal/domain/staff"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurement is a mock of Measurement interface.
type MockMeasurement struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementMockRecorder
	isgomock struct{}
}

// MockMeasurementMockRecorder is the mock recorder for MockMeasurement.
type MockMeasurementMockRecorder struct {
	mock *MockMeasurement
}

// NewMockMeasurement creates a new mock instance.
func NewMockMeasurement(ctrl *gomock.Controller) *MockMeasurement {
	mock := &MockMeasurement{ctrl: ctrl}
	mock.recorder = &MockMeasurementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurement) EXPECT() *MockMeasurementMockRecorder {
	return m.recorder
}

// AgeAtMeasurement mocks base method.
func (m *MockMeasurement) AgeAtMeasurement() measurement.AgeAtMeasurement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgeAtMeasurement")
	ret0, _ := ret[0].(measurement.AgeAtMeasurement)
	return ret0
}

// AgeAtMeasurement indicates an expected call of AgeAtMeasurement.
func (mr *MockMeasurementMockRecorder) AgeAtMeasurement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgeAtMeasurement", reflect.TypeOf((*MockMeasurement)(nil).AgeAtMeasurement))
}

// CreatedAt mocks base method.
func (m *MockMeasurement) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockMeasurementMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockMeasurement)(nil).CreatedAt))
}

// CustomerID mocks base method.
func (m *MockMeasurement) CustomerID() customer.CustomerID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerID")
	ret0, _ := ret[0].(customer.CustomerID)
	return ret0
}

// CustomerID indicates an expected call of CustomerID.
func (mr *MockMeasurementMockRecorder) CustomerID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerID", reflect.TypeOf((*MockMeasurement)(nil).CustomerID))
}

// Entries mocks base method.
func (m *MockMeasurement) Entries() []measurement.MeasurementEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Entries")
	ret0, _ := ret[0].([]measurement.MeasurementEntry)
	return ret0
}

// Entries indicates an expected call of Entries.
func (mr *MockMeasurementMockRecorder) Entries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockMeasurement)(nil).Entries))
}

// ID mocks base method.
func (m *MockMeasurement) ID() measurement.MeasurementID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(measurement.MeasurementID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockMeasurementMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockMeasurement)(nil).ID))
}

// IsDraft mocks base method.
func (m *MockMeasurement) IsDraft() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDraft")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDraft indicates an expected call of IsDraft.
func (mr *MockMeasurementMockRecorder) IsDraft() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDraft", reflect.TypeOf((*MockMeasurement)(nil).IsDraft))
}

// MeasuredBy mocks base method.
func (m *MockMeasurement) MeasuredBy() staff.StaffID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredBy")
	ret0, _ := ret[0].(staff.StaffID)
	return ret0
}

// MeasuredBy indicates an expected call of MeasuredBy.
func (mr *MockMeasurementMockRecorder) MeasuredBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredBy", reflect.TypeOf((*MockMeasurement)(nil).MeasuredBy))
}

// MeasuredOn mocks base method.
func (m *MockMeasurement) MeasuredOn() measurement.MeasuredOn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredOn")
	ret0, _ := ret[0].(measurement.MeasuredOn)
	return ret0
}

// MeasuredOn indicates an expected call of MeasuredOn.
func (mr *MockMeasurementMockRecorder) MeasuredOn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredOn", reflect.TypeOf((*MockMeasurement)(nil).MeasuredOn))
}

// Update mocks base method.
func (m *MockMeasurement) Update(measuredOn measurement.MeasuredOn, measuredBy staff.StaffID, ageAtMeasurement measurement.AgeAtMeasurement, updatedBy staff.StaffID, isDraft bool, entries []measurement.MeasurementEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", measuredOn, measuredBy, ageAtMeasurement, updatedBy, isDraft, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMeasurementMockRecorder) Update(measuredOn, measuredBy, ageAtMeasurement, updatedBy, isDraft, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeasurement)(nil).Update), measuredOn, measuredBy, ageAtMeasurement, updatedBy, isDraft, entries)
}

// UpdatedAt mocks base method.
func (m *MockMeasurement) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockMeasurementMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockMeasurement)(nil).UpdatedAt))
}

// UpdatedBy mocks base method.
func (m *MockMeasurement) UpdatedBy() staff.StaffID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedBy")
	ret0, _ := ret[0].(staff.StaffID)
	return ret0
}

// UpdatedBy indicates an expected call of UpdatedBy.
func (mr *MockMeasurementMockRecorder) UpdatedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedBy", reflect.TypeOf((*MockMeasurement)(nil).UpdatedBy))
}
