// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/measurement/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/measurement/usecase.go -destination=mocks/application/measurement/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	measurement "github.com/qkitzero/fitness-service/internal/application/measurement"
	customer "github.com/qkitzero/fitness-service/internal/domain/customer"
	measurement0 "github.com/qkitzero/fitness-service/internal/domain/measurement"
	staff "github.com/qkitzero/fitness-service/internal/domain/staff"
	gomock "go.uber.org/mock/gomock"
)

// MockMeasurementUsecase is a mock of MeasurementUsecase interface.
type MockMeasurementUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMeasurementUsecaseMockRecorder
	isgomock struct{}
}

// MockMeasurementUsecaseMockRecorder is the mock recorder for MockMeasurementUsecase.
type MockMeasurementUsecaseMockRecorder struct {
	mock *MockMeasurementUsecase
}

// NewMockMeasurementUsecase creates a new mock instance.
func NewMockMeasurementUsecase(ctrl *gomock.Controller) *MockMeasurementUsecase {
	mock := &MockMeasurementUsecase{ctrl: ctrl}
	mock.recorder = &MockMeasurementUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeasurementUsecase) EXPECT() *MockMeasurementUsecaseMockRecorder {
	return m.recorder
}

// CreateMeasurement mocks base method.
func (m *MockMeasurementUsecase) CreateMeasurement(ctx context.Context, customerID customer.CustomerID, measuredOn measurement0.MeasuredOn, measuredBy staff.StaffID, isDraft bool, entryInputs []measurement.MeasurementEntryInput) (measurement0.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeasurement", ctx, customerID, measuredOn, measuredBy, isDraft, entryInputs)
	ret0, _ := ret[0].(measurement0.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeasurement indicates an expected call of CreateMeasurement.
func (mr *MockMeasurementUsecaseMockRecorder) CreateMeasurement(ctx, customerID, measuredOn, measuredBy, isDraft, entryInputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeasurement", reflect.TypeOf((*MockMeasurementUsecase)(nil).CreateMeasurement), ctx, customerID, measuredOn, measuredBy, isDraft, entryInputs)
}

// DeleteMeasurement mocks base method.
func (m *MockMeasurementUsecase) DeleteMeasurement(ctx context.Context, measurementID measurement0.MeasurementID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMeasurement", ctx, measurementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMeasurement indicates an expected call of DeleteMeasurement.
func (mr *MockMeasurementUsecaseMockRecorder) DeleteMeasurement(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMeasurement", reflect.TypeOf((*MockMeasurementUsecase)(nil).DeleteMeasurement), ctx, measurementID)
}

// GetMeasurement mocks base method.
func (m *MockMeasurementUsecase) GetMeasurement(ctx context.Context, measurementID measurement0.MeasurementID) (measurement0.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeasurement", ctx, measurementID)
	ret0, _ := ret[0].(measurement0.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeasurement indicates an expected call of GetMeasurement.
func (mr *MockMeasurementUsecaseMockRecorder) GetMeasurement(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeasurement", reflect.TypeOf((*MockMeasurementUsecase)(nil).GetMeasurement), ctx, measurementID)
}

// ListMeasurements mocks base method.
func (m *MockMeasurementUsecase) ListMeasurements(ctx context.Context, customerID customer.CustomerID) ([]measurement0.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeasurements", ctx, customerID)
	ret0, _ := ret[0].([]measurement0.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeasurements indicates an expected call of ListMeasurements.
func (mr *MockMeasurementUsecaseMockRecorder) ListMeasurements(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeasurements", reflect.TypeOf((*MockMeasurementUsecase)(nil).ListMeasurements), ctx, customerID)
}

// UpdateMeasurement mocks base method.
func (m *MockMeasurementUsecase) UpdateMeasurement(ctx context.Context, measurementID measurement0.MeasurementID, measuredOn measurement0.MeasuredOn, measuredBy staff.StaffID, isDraft bool, entryInputs []measurement.MeasurementEntryInput) (measurement0.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeasurement", ctx, measurementID, measuredOn, measuredBy, isDraft, entryInputs)
	ret0, _ := ret[0].(measurement0.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMeasurement indicates an expected call of UpdateMeasurement.
func (mr *MockMeasurementUsecaseMockRecorder) UpdateMeasurement(ctx, measurementID, measuredOn, measuredBy, isDraft, entryInputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeasurement", reflect.TypeOf((*MockMeasurementUsecase)(nil).UpdateMeasurement), ctx, measurementID, measuredOn, measuredBy, isDraft, entryInputs)
}
