// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/organization/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/organization/usecase.go -destination=mocks/application/organization/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	organization "github.com/qkitzero/fitness-service/internal/domain/organization"
	tenant "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationUsecase is a mock of OrganizationUsecase interface.
type MockOrganizationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationUsecaseMockRecorder
	isgomock struct{}
}

// MockOrganizationUsecaseMockRecorder is the mock recorder for MockOrganizationUsecase.
type MockOrganizationUsecaseMockRecorder struct {
	mock *MockOrganizationUsecase
}

// NewMockOrganizationUsecase creates a new mock instance.
func NewMockOrganizationUsecase(ctrl *gomock.Controller) *MockOrganizationUsecase {
	mock := &MockOrganizationUsecase{ctrl: ctrl}
	mock.recorder = &MockOrganizationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationUsecase) EXPECT() *MockOrganizationUsecaseMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationUsecase) CreateOrganization(ctx context.Context, tenantID tenant.TenantID, name organization.Name) (organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, tenantID, name)
	ret0, _ := ret[0].(organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationUsecaseMockRecorder) CreateOrganization(ctx, tenantID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationUsecase)(nil).CreateOrganization), ctx, tenantID, name)
}

// DeleteOrganization mocks base method.
func (m *MockOrganizationUsecase) DeleteOrganization(ctx context.Context, organizationID organization.OrganizationID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, organizationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockOrganizationUsecaseMockRecorder) DeleteOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockOrganizationUsecase)(nil).DeleteOrganization), ctx, organizationID)
}

// GetOrganization mocks base method.
func (m *MockOrganizationUsecase) GetOrganization(ctx context.Context, organizationID organization.OrganizationID) (organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, organizationID)
	ret0, _ := ret[0].(organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockOrganizationUsecaseMockRecorder) GetOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockOrganizationUsecase)(nil).GetOrganization), ctx, organizationID)
}

// ListOrganizations mocks base method.
func (m *MockOrganizationUsecase) ListOrganizations(ctx context.Context, tenantID tenant.TenantID) ([]organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx, tenantID)
	ret0, _ := ret[0].([]organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationUsecaseMockRecorder) ListOrganizations(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationUsecase)(nil).ListOrganizations), ctx, tenantID)
}

// UpdateOrganization mocks base method.
func (m *MockOrganizationUsecase) UpdateOrganization(ctx context.Context, organizationID organization.OrganizationID, name organization.Name) (organization.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, organizationID, name)
	ret0, _ := ret[0].(organization.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockOrganizationUsecaseMockRecorder) UpdateOrganization(ctx, organizationID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockOrganizationUsecase)(nil).UpdateOrganization), ctx, organizationID, name)
}
