syntax = "proto3";

package customer.v1;

import "google/api/annotations.proto";
import "google/type/date.proto";

option go_package = "github.com/qkitzero/fitness-service/gen/go/customer/v1";

service CustomerService {
  rpc CreateCustomer(CreateCustomerRequest) returns (CreateCustomerResponse) {
    option (google.api.http) = {
      post: "/v1/customer"
      body: "*"
    };
  }
  rpc GetCustomer(GetCustomerRequest) returns (GetCustomerResponse) {
    option (google.api.http) = {get: "/v1/customer/{customer_id}"};
  }
  rpc ListCustomers(ListCustomersRequest) returns (ListCustomersResponse) {
    option (google.api.http) = {get: "/v1/customers"};
  }
  rpc UpdateCustomer(UpdateCustomerRequest) returns (UpdateCustomerResponse) {
    option (google.api.http) = {
      put: "/v1/customer/{customer_id}"
      body: "*"
    };
  }
  rpc DeleteCustomer(DeleteCustomerRequest) returns (DeleteCustomerResponse) {
    option (google.api.http) = {delete: "/v1/customer/{customer_id}"};
  }
}

enum Gender {
  GENDER_UNSPECIFIED = 0;
  GENDER_MALE = 1;
  GENDER_FEMALE = 2;
  GENDER_OTHER = 3;
}

message Customer {
  string customer_id = 1;
  string name = 2;
  string group_id = 3;
  string name_kana = 4;
  Gender gender = 5;
  google.type.Date birth_date = 6;
  optional string phone = 7;
  optional string email = 8;
  optional string postal_code = 9;
  optional string prefecture = 10;
  optional string city = 11;
  optional string street = 12;
  optional string building = 13;
  optional string emergency_contact_name = 14;
  optional string emergency_contact_relationship = 15;
  optional string emergency_contact_phone = 16;
}

message CreateCustomerRequest {
  string name = 1;
  string group_id = 2;
  string name_kana = 3;
  Gender gender = 4;
  google.type.Date birth_date = 5;
  optional string phone = 6;
  optional string email = 7;
  optional string postal_code = 8;
  optional string prefecture = 9;
  optional string city = 10;
  optional string street = 11;
  optional string building = 12;
  optional string emergency_contact_name = 13;
  optional string emergency_contact_relationship = 14;
  optional string emergency_contact_phone = 15;
}

message CreateCustomerResponse {
  string customer_id = 1;
}

message GetCustomerRequest {
  string customer_id = 1;
}

message GetCustomerResponse {
  Customer customer = 1;
}

message ListCustomersRequest {
  string group_id = 1;
}

message ListCustomersResponse {
  repeated Customer customers = 1;
}

message UpdateCustomerRequest {
  string customer_id = 1;
  string name = 2;
  string name_kana = 3;
  Gender gender = 4;
  google.type.Date birth_date = 5;
  optional string phone = 6;
  optional string email = 7;
  optional string postal_code = 8;
  optional string prefecture = 9;
  optional string city = 10;
  optional string street = 11;
  optional string building = 12;
  optional string emergency_contact_name = 13;
  optional string emergency_contact_relationship = 14;
  optional string emergency_contact_phone = 15;
}

message UpdateCustomerResponse {
  Customer customer = 1;
}

message DeleteCustomerRequest {
  string customer_id = 1;
}

message DeleteCustomerResponse {}
