syntax = "proto3";

package organization.v1;

import "google/api/annotations.proto";

option go_package = "github.com/qkitzero/fitness-service/gen/go/organization/v1";

service OrganizationService {
  rpc CreateOrganization(CreateOrganizationRequest) returns (CreateOrganizationResponse) {
    option (google.api.http) = {
      post: "/v1/organization"
      body: "*"
    };
  }
  rpc GetOrganization(GetOrganizationRequest) returns (GetOrganizationResponse) {
    option (google.api.http) = {get: "/v1/organization/{organization_id}"};
  }
  rpc ListOrganizations(ListOrganizationsRequest) returns (ListOrganizationsResponse) {
    option (google.api.http) = {get: "/v1/organizations"};
  }
  rpc UpdateOrganization(UpdateOrganizationRequest) returns (UpdateOrganizationResponse) {
    option (google.api.http) = {
      put: "/v1/organization/{organization_id}"
      body: "*"
    };
  }
  rpc DeleteOrganization(DeleteOrganizationRequest) returns (DeleteOrganizationResponse) {
    option (google.api.http) = {delete: "/v1/organization/{organization_id}"};
  }
}

message Organization {
  string organization_id = 1;
  string tenant_id = 2;
  string name = 3;
}

message CreateOrganizationRequest {
  string tenant_id = 1;
  string name = 2;
}

message CreateOrganizationResponse {
  string organization_id = 1;
}

message GetOrganizationRequest {
  string organization_id = 1;
}

message GetOrganizationResponse {
  Organization organization = 1;
}

message ListOrganizationsRequest {
  string tenant_id = 1;
}

message ListOrganizationsResponse {
  repeated Organization organizations = 1;
}

message UpdateOrganizationRequest {
  string organization_id = 1;
  string name = 2;
}

message UpdateOrganizationResponse {
  Organization organization = 1;
}

message DeleteOrganizationRequest {
  string organization_id = 1;
}

message DeleteOrganizationResponse {}
