// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/repository.go -destination=mocks/domain/judgment/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	gomock "go.uber.org/mock/gomock"
)

// MockJudgmentRepository is a mock of JudgmentRepository interface.
type MockJudgmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJudgmentRepositoryMockRecorder
	isgomock struct{}
}

// MockJudgmentRepositoryMockRecorder is the mock recorder for MockJudgmentRepository.
type MockJudgmentRepositoryMockRecorder struct {
	mock *MockJudgmentRepository
}

// NewMockJudgmentRepository creates a new mock instance.
func NewMockJudgmentRepository(ctrl *gomock.Controller) *MockJudgmentRepository {
	mock := &MockJudgmentRepository{ctrl: ctrl}
	mock.recorder = &MockJudgmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudgmentRepository) EXPECT() *MockJudgmentRepositoryMockRecorder {
	return m.recorder
}

// FindByMeasurementID mocks base method.
func (m *MockJudgmentRepository) FindByMeasurementID(ctx context.Context, measurementID measurement.MeasurementID) (judgment.Judgment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByMeasurementID", ctx, measurementID)
	ret0, _ := ret[0].(judgment.Judgment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByMeasurementID indicates an expected call of FindByMeasurementID.
func (mr *MockJudgmentRepositoryMockRecorder) FindByMeasurementID(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByMeasurementID", reflect.TypeOf((*MockJudgmentRepository)(nil).FindByMeasurementID), ctx, measurementID)
}

// Upsert mocks base method.
func (m *MockJudgmentRepository) Upsert(ctx context.Context, arg1 judgment.Judgment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockJudgmentRepositoryMockRecorder) Upsert(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockJudgmentRepository)(nil).Upsert), ctx, arg1)
}
