// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/prescription.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/prescription.go -destination=mocks/domain/judgment/mock_prescription.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	gomock "go.uber.org/mock/gomock"
)

// MockPrescription is a mock of Prescription interface.
type MockPrescription struct {
	ctrl     *gomock.Controller
	recorder *MockPrescriptionMockRecorder
	isgomock struct{}
}

// MockPrescriptionMockRecorder is the mock recorder for MockPrescription.
type MockPrescriptionMockRecorder struct {
	mock *MockPrescription
}

// NewMockPrescription creates a new mock instance.
func NewMockPrescription(ctrl *gomock.Controller) *MockPrescription {
	mock := &MockPrescription{ctrl: ctrl}
	mock.recorder = &MockPrescriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescription) EXPECT() *MockPrescriptionMockRecorder {
	return m.recorder
}

// PrescribedMenus mocks base method.
func (m *MockPrescription) PrescribedMenus() []judgment.PrescribedMenu {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrescribedMenus")
	ret0, _ := ret[0].([]judgment.PrescribedMenu)
	return ret0
}

// PrescribedMenus indicates an expected call of PrescribedMenus.
func (mr *MockPrescriptionMockRecorder) PrescribedMenus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrescribedMenus", reflect.TypeOf((*MockPrescription)(nil).PrescribedMenus))
}
