// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/prescribed_menu_override_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/prescribed_menu_override_repository.go -destination=mocks/domain/judgment/mock_prescribed_menu_override_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	gomock "go.uber.org/mock/gomock"
)

// MockPrescribedMenuOverrideRepository is a mock of PrescribedMenuOverrideRepository interface.
type MockPrescribedMenuOverrideRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrescribedMenuOverrideRepositoryMockRecorder
	isgomock struct{}
}

// MockPrescribedMenuOverrideRepositoryMockRecorder is the mock recorder for MockPrescribedMenuOverrideRepository.
type MockPrescribedMenuOverrideRepositoryMockRecorder struct {
	mock *MockPrescribedMenuOverrideRepository
}

// NewMockPrescribedMenuOverrideRepository creates a new mock instance.
func NewMockPrescribedMenuOverrideRepository(ctrl *gomock.Controller) *MockPrescribedMenuOverrideRepository {
	mock := &MockPrescribedMenuOverrideRepository{ctrl: ctrl}
	mock.recorder = &MockPrescribedMenuOverrideRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescribedMenuOverrideRepository) EXPECT() *MockPrescribedMenuOverrideRepositoryMockRecorder {
	return m.recorder
}

// DeleteByMeasurementID mocks base method.
func (m *MockPrescribedMenuOverrideRepository) DeleteByMeasurementID(ctx context.Context, measurementID measurement.MeasurementID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMeasurementID", ctx, measurementID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMeasurementID indicates an expected call of DeleteByMeasurementID.
func (mr *MockPrescribedMenuOverrideRepositoryMockRecorder) DeleteByMeasurementID(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMeasurementID", reflect.TypeOf((*MockPrescribedMenuOverrideRepository)(nil).DeleteByMeasurementID), ctx, measurementID)
}

// ListByMeasurementID mocks base method.
func (m *MockPrescribedMenuOverrideRepository) ListByMeasurementID(ctx context.Context, measurementID measurement.MeasurementID) ([]judgment.PrescribedMenuOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMeasurementID", ctx, measurementID)
	ret0, _ := ret[0].([]judgment.PrescribedMenuOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMeasurementID indicates an expected call of ListByMeasurementID.
func (mr *MockPrescribedMenuOverrideRepositoryMockRecorder) ListByMeasurementID(ctx, measurementID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMeasurementID", reflect.TypeOf((*MockPrescribedMenuOverrideRepository)(nil).ListByMeasurementID), ctx, measurementID)
}

// ReplaceByMeasurementID mocks base method.
func (m *MockPrescribedMenuOverrideRepository) ReplaceByMeasurementID(ctx context.Context, measurementID measurement.MeasurementID, overrides []judgment.PrescribedMenuOverride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceByMeasurementID", ctx, measurementID, overrides)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceByMeasurementID indicates an expected call of ReplaceByMeasurementID.
func (mr *MockPrescribedMenuOverrideRepositoryMockRecorder) ReplaceByMeasurementID(ctx, measurementID, overrides any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceByMeasurementID", reflect.TypeOf((*MockPrescribedMenuOverrideRepository)(nil).ReplaceByMeasurementID), ctx, measurementID, overrides)
}
