// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/judgment.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/judgment.go -destination=mocks/domain/judgment/mock_judgment.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	gomock "go.uber.org/mock/gomock"
)

// MockJudgment is a mock of Judgment interface.
type MockJudgment struct {
	ctrl     *gomock.Controller
	recorder *MockJudgmentMockRecorder
	isgomock struct{}
}

// MockJudgmentMockRecorder is the mock recorder for MockJudgment.
type MockJudgmentMockRecorder struct {
	mock *MockJudgment
}

// NewMockJudgment creates a new mock instance.
func NewMockJudgment(ctrl *gomock.Controller) *MockJudgment {
	mock := &MockJudgment{ctrl: ctrl}
	mock.recorder = &MockJudgmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudgment) EXPECT() *MockJudgmentMockRecorder {
	return m.recorder
}

// Advice mocks base method.
func (m *MockJudgment) Advice() *judgment.Advice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Advice")
	ret0, _ := ret[0].(*judgment.Advice)
	return ret0
}

// Advice indicates an expected call of Advice.
func (mr *MockJudgmentMockRecorder) Advice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advice", reflect.TypeOf((*MockJudgment)(nil).Advice))
}

// CreatedAt mocks base method.
func (m *MockJudgment) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockJudgmentMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockJudgment)(nil).CreatedAt))
}

// MeasurementID mocks base method.
func (m *MockJudgment) MeasurementID() measurement.MeasurementID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasurementID")
	ret0, _ := ret[0].(measurement.MeasurementID)
	return ret0
}

// MeasurementID indicates an expected call of MeasurementID.
func (mr *MockJudgmentMockRecorder) MeasurementID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasurementID", reflect.TypeOf((*MockJudgment)(nil).MeasurementID))
}

// Update mocks base method.
func (m *MockJudgment) Update(advice *judgment.Advice) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", advice)
}

// Update indicates an expected call of Update.
func (mr *MockJudgmentMockRecorder) Update(advice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJudgment)(nil).Update), advice)
}

// UpdatedAt mocks base method.
func (m *MockJudgment) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockJudgmentMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockJudgment)(nil).UpdatedAt))
}
