// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/prescribed_menu.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/prescribed_menu.go -destination=mocks/domain/judgment/mock_prescribed_menu.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockPrescribedMenu is a mock of PrescribedMenu interface.
type MockPrescribedMenu struct {
	ctrl     *gomock.Controller
	recorder *MockPrescribedMenuMockRecorder
	isgomock struct{}
}

// MockPrescribedMenuMockRecorder is the mock recorder for MockPrescribedMenu.
type MockPrescribedMenuMockRecorder struct {
	mock *MockPrescribedMenu
}

// NewMockPrescribedMenu creates a new mock instance.
func NewMockPrescribedMenu(ctrl *gomock.Controller) *MockPrescribedMenu {
	mock := &MockPrescribedMenu{ctrl: ctrl}
	mock.recorder = &MockPrescribedMenuMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescribedMenu) EXPECT() *MockPrescribedMenuMockRecorder {
	return m.recorder
}

// Amount mocks base method.
func (m *MockPrescribedMenu) Amount() training.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Amount")
	ret0, _ := ret[0].(training.Amount)
	return ret0
}

// Amount indicates an expected call of Amount.
func (mr *MockPrescribedMenuMockRecorder) Amount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Amount", reflect.TypeOf((*MockPrescribedMenu)(nil).Amount))
}

// Element mocks base method.
func (m *MockPrescribedMenu) Element() *measurementitem.Element {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Element")
	ret0, _ := ret[0].(*measurementitem.Element)
	return ret0
}

// Element indicates an expected call of Element.
func (mr *MockPrescribedMenuMockRecorder) Element() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Element", reflect.TypeOf((*MockPrescribedMenu)(nil).Element))
}

// Part mocks base method.
func (m *MockPrescribedMenu) Part() *training.Part {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Part")
	ret0, _ := ret[0].(*training.Part)
	return ret0
}

// Part indicates an expected call of Part.
func (mr *MockPrescribedMenuMockRecorder) Part() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Part", reflect.TypeOf((*MockPrescribedMenu)(nil).Part))
}

// Sets mocks base method.
func (m *MockPrescribedMenu) Sets() training.Sets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sets")
	ret0, _ := ret[0].(training.Sets)
	return ret0
}

// Sets indicates an expected call of Sets.
func (mr *MockPrescribedMenuMockRecorder) Sets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sets", reflect.TypeOf((*MockPrescribedMenu)(nil).Sets))
}

// Source mocks base method.
func (m *MockPrescribedMenu) Source() judgment.PrescriptionSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(judgment.PrescriptionSource)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockPrescribedMenuMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockPrescribedMenu)(nil).Source))
}

// TrainingMenuID mocks base method.
func (m *MockPrescribedMenu) TrainingMenuID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// TrainingMenuID indicates an expected call of TrainingMenuID.
func (mr *MockPrescribedMenuMockRecorder) TrainingMenuID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuID", reflect.TypeOf((*MockPrescribedMenu)(nil).TrainingMenuID))
}

// TrainingMenuName mocks base method.
func (m *MockPrescribedMenu) TrainingMenuName() training.Name {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuName")
	ret0, _ := ret[0].(training.Name)
	return ret0
}

// TrainingMenuName indicates an expected call of TrainingMenuName.
func (mr *MockPrescribedMenuMockRecorder) TrainingMenuName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuName", reflect.TypeOf((*MockPrescribedMenu)(nil).TrainingMenuName))
}

// Unit mocks base method.
func (m *MockPrescribedMenu) Unit() training.Unit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unit")
	ret0, _ := ret[0].(training.Unit)
	return ret0
}

// Unit indicates an expected call of Unit.
func (mr *MockPrescribedMenuMockRecorder) Unit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unit", reflect.TypeOf((*MockPrescribedMenu)(nil).Unit))
}
