// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/judgment/prescribed_menu_override.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/judgment/prescribed_menu_override.go -destination=mocks/domain/judgment/mock_prescribed_menu_override.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	judgment "github.com/qkitzero/fitness-service/internal/domain/judgment"
	measurement "github.com/qkitzero/fitness-service/internal/domain/measurement"
	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	training "github.com/qkitzero/fitness-service/internal/domain/training"
	gomock "go.uber.org/mock/gomock"
)

// MockPrescribedMenuOverride is a mock of PrescribedMenuOverride interface.
type MockPrescribedMenuOverride struct {
	ctrl     *gomock.Controller
	recorder *MockPrescribedMenuOverrideMockRecorder
	isgomock struct{}
}

// MockPrescribedMenuOverrideMockRecorder is the mock recorder for MockPrescribedMenuOverride.
type MockPrescribedMenuOverrideMockRecorder struct {
	mock *MockPrescribedMenuOverride
}

// NewMockPrescribedMenuOverride creates a new mock instance.
func NewMockPrescribedMenuOverride(ctrl *gomock.Controller) *MockPrescribedMenuOverride {
	mock := &MockPrescribedMenuOverride{ctrl: ctrl}
	mock.recorder = &MockPrescribedMenuOverrideMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrescribedMenuOverride) EXPECT() *MockPrescribedMenuOverrideMockRecorder {
	return m.recorder
}

// Amount mocks base method.
func (m *MockPrescribedMenuOverride) Amount() training.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Amount")
	ret0, _ := ret[0].(training.Amount)
	return ret0
}

// Amount indicates an expected call of Amount.
func (mr *MockPrescribedMenuOverrideMockRecorder) Amount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Amount", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).Amount))
}

// CreatedAt mocks base method.
func (m *MockPrescribedMenuOverride) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockPrescribedMenuOverrideMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).CreatedAt))
}

// Element mocks base method.
func (m *MockPrescribedMenuOverride) Element() *measurementitem.Element {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Element")
	ret0, _ := ret[0].(*measurementitem.Element)
	return ret0
}

// Element indicates an expected call of Element.
func (mr *MockPrescribedMenuOverrideMockRecorder) Element() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Element", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).Element))
}

// ID mocks base method.
func (m *MockPrescribedMenuOverride) ID() judgment.PrescribedMenuOverrideID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(judgment.PrescribedMenuOverrideID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockPrescribedMenuOverrideMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).ID))
}

// MeasurementID mocks base method.
func (m *MockPrescribedMenuOverride) MeasurementID() measurement.MeasurementID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasurementID")
	ret0, _ := ret[0].(measurement.MeasurementID)
	return ret0
}

// MeasurementID indicates an expected call of MeasurementID.
func (mr *MockPrescribedMenuOverrideMockRecorder) MeasurementID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasurementID", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).MeasurementID))
}

// Part mocks base method.
func (m *MockPrescribedMenuOverride) Part() *training.Part {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Part")
	ret0, _ := ret[0].(*training.Part)
	return ret0
}

// Part indicates an expected call of Part.
func (mr *MockPrescribedMenuOverrideMockRecorder) Part() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Part", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).Part))
}

// Sets mocks base method.
func (m *MockPrescribedMenuOverride) Sets() training.Sets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sets")
	ret0, _ := ret[0].(training.Sets)
	return ret0
}

// Sets indicates an expected call of Sets.
func (mr *MockPrescribedMenuOverrideMockRecorder) Sets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sets", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).Sets))
}

// SortOrder mocks base method.
func (m *MockPrescribedMenuOverride) SortOrder() training.SortOrder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortOrder")
	ret0, _ := ret[0].(training.SortOrder)
	return ret0
}

// SortOrder indicates an expected call of SortOrder.
func (mr *MockPrescribedMenuOverrideMockRecorder) SortOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortOrder", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).SortOrder))
}

// TrainingMenuID mocks base method.
func (m *MockPrescribedMenuOverride) TrainingMenuID() training.TrainingMenuID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrainingMenuID")
	ret0, _ := ret[0].(training.TrainingMenuID)
	return ret0
}

// TrainingMenuID indicates an expected call of TrainingMenuID.
func (mr *MockPrescribedMenuOverrideMockRecorder) TrainingMenuID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrainingMenuID", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).TrainingMenuID))
}

// Unit mocks base method.
func (m *MockPrescribedMenuOverride) Unit() training.Unit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unit")
	ret0, _ := ret[0].(training.Unit)
	return ret0
}

// Unit indicates an expected call of Unit.
func (mr *MockPrescribedMenuOverrideMockRecorder) Unit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unit", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).Unit))
}

// UpdatedAt mocks base method.
func (m *MockPrescribedMenuOverride) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockPrescribedMenuOverrideMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockPrescribedMenuOverride)(nil).UpdatedAt))
}
