// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/standard/rank_standard.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/standard/rank_standard.go -destination=mocks/domain/standard/mock_rank_standard.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	standard "github.com/qkitzero/fitness-service/internal/domain/standard"
	gomock "go.uber.org/mock/gomock"
)

// MockRankStandard is a mock of RankStandard interface.
type MockRankStandard struct {
	ctrl     *gomock.Controller
	recorder *MockRankStandardMockRecorder
	isgomock struct{}
}

// MockRankStandardMockRecorder is the mock recorder for MockRankStandard.
type MockRankStandardMockRecorder struct {
	mock *MockRankStandard
}

// NewMockRankStandard creates a new mock instance.
func NewMockRankStandard(ctrl *gomock.Controller) *MockRankStandard {
	mock := &MockRankStandard{ctrl: ctrl}
	mock.recorder = &MockRankStandardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankStandard) EXPECT() *MockRankStandardMockRecorder {
	return m.recorder
}

// CreatedAt mocks base method.
func (m *MockRankStandard) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockRankStandardMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockRankStandard)(nil).CreatedAt))
}

// Rank mocks base method.
func (m *MockRankStandard) Rank() standard.Rank {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rank")
	ret0, _ := ret[0].(standard.Rank)
	return ret0
}

// Rank indicates an expected call of Rank.
func (mr *MockRankStandardMockRecorder) Rank() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rank", reflect.TypeOf((*MockRankStandard)(nil).Rank))
}

// UpdatedAt mocks base method.
func (m *MockRankStandard) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockRankStandardMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockRankStandard)(nil).UpdatedAt))
}

// ZScoreMax mocks base method.
func (m *MockRankStandard) ZScoreMax() *standard.ZScore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZScoreMax")
	ret0, _ := ret[0].(*standard.ZScore)
	return ret0
}

// ZScoreMax indicates an expected call of ZScoreMax.
func (mr *MockRankStandardMockRecorder) ZScoreMax() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZScoreMax", reflect.TypeOf((*MockRankStandard)(nil).ZScoreMax))
}

// ZScoreMin mocks base method.
func (m *MockRankStandard) ZScoreMin() *standard.ZScore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZScoreMin")
	ret0, _ := ret[0].(*standard.ZScore)
	return ret0
}

// ZScoreMin indicates an expected call of ZScoreMin.
func (mr *MockRankStandardMockRecorder) ZScoreMin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZScoreMin", reflect.TypeOf((*MockRankStandard)(nil).ZScoreMin))
}
