// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/standard/rank_standard_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/standard/rank_standard_repository.go -destination=mocks/domain/standard/mock_rank_standard_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	standard "github.com/qkitzero/fitness-service/internal/domain/standard"
	gomock "go.uber.org/mock/gomock"
)

// MockRankStandardRepository is a mock of RankStandardRepository interface.
type MockRankStandardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRankStandardRepositoryMockRecorder
	isgomock struct{}
}

// MockRankStandardRepositoryMockRecorder is the mock recorder for MockRankStandardRepository.
type MockRankStandardRepositoryMockRecorder struct {
	mock *MockRankStandardRepository
}

// NewMockRankStandardRepository creates a new mock instance.
func NewMockRankStandardRepository(ctrl *gomock.Controller) *MockRankStandardRepository {
	mock := &MockRankStandardRepository{ctrl: ctrl}
	mock.recorder = &MockRankStandardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankStandardRepository) EXPECT() *MockRankStandardRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockRankStandardRepository) List(ctx context.Context) ([]standard.RankStandard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]standard.RankStandard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRankStandardRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRankStandardRepository)(nil).List), ctx)
}
