// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/standard/age_group_standard.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/standard/age_group_standard.go -destination=mocks/domain/standard/mock_age_group_standard.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	standard "github.com/qkitzero/fitness-service/internal/domain/standard"
	gomock "go.uber.org/mock/gomock"
)

// MockAgeGroupStandard is a mock of AgeGroupStandard interface.
type MockAgeGroupStandard struct {
	ctrl     *gomock.Controller
	recorder *MockAgeGroupStandardMockRecorder
	isgomock struct{}
}

// MockAgeGroupStandardMockRecorder is the mock recorder for MockAgeGroupStandard.
type MockAgeGroupStandardMockRecorder struct {
	mock *MockAgeGroupStandard
}

// NewMockAgeGroupStandard creates a new mock instance.
func NewMockAgeGroupStandard(ctrl *gomock.Controller) *MockAgeGroupStandard {
	mock := &MockAgeGroupStandard{ctrl: ctrl}
	mock.recorder = &MockAgeGroupStandardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgeGroupStandard) EXPECT() *MockAgeGroupStandardMockRecorder {
	return m.recorder
}

// AgeRange mocks base method.
func (m *MockAgeGroupStandard) AgeRange() standard.AgeRange {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgeRange")
	ret0, _ := ret[0].(standard.AgeRange)
	return ret0
}

// AgeRange indicates an expected call of AgeRange.
func (mr *MockAgeGroupStandardMockRecorder) AgeRange() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgeRange", reflect.TypeOf((*MockAgeGroupStandard)(nil).AgeRange))
}

// CreatedAt mocks base method.
func (m *MockAgeGroupStandard) CreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockAgeGroupStandardMockRecorder) CreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockAgeGroupStandard)(nil).CreatedAt))
}

// Gender mocks base method.
func (m *MockAgeGroupStandard) Gender() standard.Gender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gender")
	ret0, _ := ret[0].(standard.Gender)
	return ret0
}

// Gender indicates an expected call of Gender.
func (mr *MockAgeGroupStandardMockRecorder) Gender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gender", reflect.TypeOf((*MockAgeGroupStandard)(nil).Gender))
}

// ID mocks base method.
func (m *MockAgeGroupStandard) ID() standard.AgeGroupStandardID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(standard.AgeGroupStandardID)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockAgeGroupStandardMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockAgeGroupStandard)(nil).ID))
}

// Mean mocks base method.
func (m *MockAgeGroupStandard) Mean() standard.Mean {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mean")
	ret0, _ := ret[0].(standard.Mean)
	return ret0
}

// Mean indicates an expected call of Mean.
func (mr *MockAgeGroupStandardMockRecorder) Mean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mean", reflect.TypeOf((*MockAgeGroupStandard)(nil).Mean))
}

// MeasurementItemID mocks base method.
func (m *MockAgeGroupStandard) MeasurementItemID() measurementitem.MeasurementItemID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasurementItemID")
	ret0, _ := ret[0].(measurementitem.MeasurementItemID)
	return ret0
}

// MeasurementItemID indicates an expected call of MeasurementItemID.
func (mr *MockAgeGroupStandardMockRecorder) MeasurementItemID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasurementItemID", reflect.TypeOf((*MockAgeGroupStandard)(nil).MeasurementItemID))
}

// StandardDeviation mocks base method.
func (m *MockAgeGroupStandard) StandardDeviation() standard.StandardDeviation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StandardDeviation")
	ret0, _ := ret[0].(standard.StandardDeviation)
	return ret0
}

// StandardDeviation indicates an expected call of StandardDeviation.
func (mr *MockAgeGroupStandardMockRecorder) StandardDeviation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StandardDeviation", reflect.TypeOf((*MockAgeGroupStandard)(nil).StandardDeviation))
}

// UpdatedAt mocks base method.
func (m *MockAgeGroupStandard) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockAgeGroupStandardMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockAgeGroupStandard)(nil).UpdatedAt))
}
