// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/standard/age_group_standard_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/standard/age_group_standard_repository.go -destination=mocks/domain/standard/mock_age_group_standard_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	measurementitem "github.com/qkitzero/fitness-service/internal/domain/measurementitem"
	standard "github.com/qkitzero/fitness-service/internal/domain/standard"
	gomock "go.uber.org/mock/gomock"
)

// MockAgeGroupStandardRepository is a mock of AgeGroupStandardRepository interface.
type MockAgeGroupStandardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgeGroupStandardRepositoryMockRecorder
	isgomock struct{}
}

// MockAgeGroupStandardRepositoryMockRecorder is the mock recorder for MockAgeGroupStandardRepository.
type MockAgeGroupStandardRepositoryMockRecorder struct {
	mock *MockAgeGroupStandardRepository
}

// NewMockAgeGroupStandardRepository creates a new mock instance.
func NewMockAgeGroupStandardRepository(ctrl *gomock.Controller) *MockAgeGroupStandardRepository {
	mock := &MockAgeGroupStandardRepository{ctrl: ctrl}
	mock.recorder = &MockAgeGroupStandardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgeGroupStandardRepository) EXPECT() *MockAgeGroupStandardRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAgeGroupStandardRepository) List(ctx context.Context) ([]standard.AgeGroupStandard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]standard.AgeGroupStandard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgeGroupStandardRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgeGroupStandardRepository)(nil).List), ctx)
}

// ListByItemIDsAndGender mocks base method.
func (m *MockAgeGroupStandardRepository) ListByItemIDsAndGender(ctx context.Context, measurementItemIDs []measurementitem.MeasurementItemID, gender standard.Gender) ([]standard.AgeGroupStandard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByItemIDsAndGender", ctx, measurementItemIDs, gender)
	ret0, _ := ret[0].([]standard.AgeGroupStandard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByItemIDsAndGender indicates an expected call of ListByItemIDsAndGender.
func (mr *MockAgeGroupStandardRepositoryMockRecorder) ListByItemIDsAndGender(ctx, measurementItemIDs, gender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByItemIDsAndGender", reflect.TypeOf((*MockAgeGroupStandardRepository)(nil).ListByItemIDsAndGender), ctx, measurementItemIDs, gender)
}
