// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/tenant/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/tenant/usecase.go -destination=mocks/application/tenant/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tenant "github.com/qkitzero/fitness-service/internal/application/tenant"
	tenant0 "github.com/qkitzero/fitness-service/internal/domain/tenant"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileUsecase is a mock of ProfileUsecase interface.
type MockProfileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUsecaseMockRecorder
	isgomock struct{}
}

// MockProfileUsecaseMockRecorder is the mock recorder for MockProfileUsecase.
type MockProfileUsecaseMockRecorder struct {
	mock *MockProfileUsecase
}

// NewMockProfileUsecase creates a new mock instance.
func NewMockProfileUsecase(ctrl *gomock.Controller) *MockProfileUsecase {
	mock := &MockProfileUsecase{ctrl: ctrl}
	mock.recorder = &MockProfileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUsecase) EXPECT() *MockProfileUsecaseMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockProfileUsecase) GetProfile(ctx context.Context, tenantID tenant0.TenantID) (tenant0.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, tenantID)
	ret0, _ := ret[0].(tenant0.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileUsecaseMockRecorder) GetProfile(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileUsecase)(nil).GetProfile), ctx, tenantID)
}

// UpsertProfile mocks base method.
func (m *MockProfileUsecase) UpsertProfile(ctx context.Context, tenantID tenant0.TenantID, patch tenant.ProfilePatch) (tenant0.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProfile", ctx, tenantID, patch)
	ret0, _ := ret[0].(tenant0.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProfile indicates an expected call of UpsertProfile.
func (mr *MockProfileUsecaseMockRecorder) UpsertProfile(ctx, tenantID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProfile", reflect.TypeOf((*MockProfileUsecase)(nil).UpsertProfile), ctx, tenantID, patch)
}
